#include "PluginEditor.hpp"
#include "PluginProcessor.hpp"
#include <sstream>
using namespace iupac;
namespace{
domain::Node defaultNode(std::string id,const domain::ModuleDescriptor&d){domain::Node n{std::move(id),d.type,{}};for(const auto&p:d.parameters)n.parameters.push_back({std::string(p.id),std::vector<double>(p.arraySize?p.arraySize:1,p.defaultValue)});if(d.type==domain::ModuleType::harmonic)for(std::size_t i=0;i<16;++i)n.parameters[1].values[i]=double(i+1);return n;}
std::string uniqueId(const domain::Patch&p,std::string_view stem){for(int i=1;i<100;++i){auto s=std::string(stem)+std::to_string(i);if(std::ranges::none_of(p.nodes,[&](const auto&n){return n.id==s;}))return s;}return{};}
std::string uniqueRouteId(const domain::Patch&p){for(int i=1;i<=100;++i){auto s="route"+std::to_string(i);if(std::ranges::none_of(p.matrix,[&](const auto&r){return r.id==s;}))return s;}return{};}
}
struct IupacSynthEditor::ModulesModel final:juce::ListBoxModel{IupacSynthEditor&e;explicit ModulesModel(IupacSynthEditor&x):e(x){}int getNumRows()override{return(int)e.owner_.snapshot().editedPatch.nodes.size();}void paintListBoxItem(int r,juce::Graphics&g,int w,int h,bool s)override{auto p=e.owner_.snapshot().editedPatch;if(r<0||r>=(int)p.nodes.size())return;if(s)g.fillAll(juce::Colour(0xff35506f));auto&n=p.nodes[(std::size_t)r];g.setColour(juce::Colours::white);g.drawText(juce::String(n.id)+"  ["+domain::moduleCatalog()[(std::size_t)n.type].id.data()+"]",8,0,w-8,h,juce::Justification::centredLeft);}void selectedRowsChanged(int r)override{e.selectedModule_=std::max(0,r);e.refreshDetail();e.refreshGraph();}};
struct IupacSynthEditor::EdgesModel final:juce::ListBoxModel{IupacSynthEditor&e;explicit EdgesModel(IupacSynthEditor&x):e(x){}int getNumRows()override{return(int)e.owner_.snapshot().editedPatch.edges.size();}void paintListBoxItem(int i,juce::Graphics&g,int w,int h,bool s)override{auto p=e.owner_.snapshot().editedPatch;if(i<0||i>=(int)p.edges.size())return;if(s)g.fillAll(juce::Colour(0xff35506f));auto&r=p.edges[(std::size_t)i];g.setColour(juce::Colours::white);g.drawText(juce::String(r.source)+" -> "+r.destination+"  gain "+juce::String(r.gain,3),8,0,w-8,h,juce::Justification::centredLeft);}void selectedRowsChanged(int r)override{e.selectedEdge_=std::max(0,r);}};
struct IupacSynthEditor::MatrixModel final:juce::ListBoxModel{IupacSynthEditor&e;explicit MatrixModel(IupacSynthEditor&x):e(x){}int getNumRows()override{return(int)e.owner_.snapshot().editedPatch.matrix.size();}void paintListBoxItem(int i,juce::Graphics&g,int w,int h,bool s)override{auto p=e.owner_.snapshot().editedPatch;if(i<0||i>=(int)p.matrix.size())return;if(s)g.fillAll(juce::Colour(0xff35506f));auto&r=p.matrix[(std::size_t)i];g.setColour(r.enabled?juce::Colours::white:juce::Colours::grey);g.drawText(juce::String(r.id)+": "+sourceName((int)r.source)+" -> "+r.destinationNode+"."+r.destinationParameter+"  "+juce::String(r.depth,3),8,0,w-8,h,juce::Justification::centredLeft);}void selectedRowsChanged(int r)override{e.selectedRow_=std::max(0,r);auto p=e.owner_.snapshot().editedPatch;if(r<0||r>=(int)p.matrix.size())return;const auto&row=p.matrix[(std::size_t)r];e.matrixSource_.setSelectedItemIndex((int)row.source,juce::dontSendNotification);e.matrixDestination_.setText(juce::String(row.destinationNode)+"."+row.destinationParameter,juce::dontSendNotification);e.matrixDepth_.setValue(row.depth,juce::dontSendNotification);e.matrixEnabled_.setToggleState(row.enabled,juce::dontSendNotification);}};
IupacSynthEditor::IupacSynthEditor(IupacSynthProcessor&o):AudioProcessorEditor(o),owner_(o),keyboard_(o.keyboardState(),juce::MidiKeyboardComponent::horizontalKeyboard){
 setTitle("IUPAC Synth 2 manual editor");setDescription("Chemistry-independent modular synthesizer editor");
 for(auto*c:std::array<juce::Component*,11>{&newButton_,&loadButton_,&saveButton_,&savePresetButton_,&resetPatchButton_,&resetControlsButton_,&presetList_,&status_,&meter_,&tabs_,&keyboard_})addAndMakeVisible(c);
 status_.setText("Manual synth ready",juce::dontSendNotification);status_.setName("Editor action status");status_.setColour(juce::Label::textColourId,juce::Colours::lightgreen);meter_.setName("Output meter, active voices, and audible generation");meter_.setJustificationType(juce::Justification::centredRight);keyboard_.setName("Audition keyboard");keyboard_.setWantsKeyboardFocus(false);moduleList_.setName("Patch modules");edgeList_.setName("Audio connections");matrixList_.setName("Modulation routes");addType_.setName("Module type");edgeSource_.setName("Audio source");edgeDestination_.setName("Audio destination");edgeGain_.setName("Audio connection gain");matrixSource_.setName("Modulation source");matrixDestination_.setName("Modulation destination");matrixDepth_.setName("Modulation depth");presetList_.setName("File-backed preset library");
 tabs_.addTab("Modules & audio",juce::Colour(0xff20242c),&modulesTab_,false);tabs_.addTab("Modulation matrix",juce::Colour(0xff20242c),&matrixTab_,false);modulesModel_=std::make_unique<ModulesModel>(*this);edgesModel_=std::make_unique<EdgesModel>(*this);matrixModel_=std::make_unique<MatrixModel>(*this);moduleList_.setModel(modulesModel_.get());edgeList_.setModel(edgesModel_.get());matrixList_.setModel(matrixModel_.get());
 for(auto*c:std::array<juce::Component*,12>{&moduleList_,&addType_,&addModuleButton_,&removeModuleButton_,&edgeList_,&edgeSource_,&edgeDestination_,&edgeGain_,&addEdgeButton_,&removeEdgeButton_,&graph_,&detailViewport_})modulesTab_.addAndMakeVisible(c);for(auto*c:std::array<juce::Component*,8>{&matrixList_,&matrixSource_,&matrixDestination_,&matrixDepth_,&matrixEnabled_,&addRowButton_,&updateRowButton_,&removeRowButton_})matrixTab_.addAndMakeVisible(c);detailViewport_.setViewedComponent(&detailContent_,false);graph_.setColour(juce::Label::backgroundColourId,juce::Colour(0xff111419));graph_.setJustificationType(juce::Justification::topLeft);
 int item=1;for(const auto&d:domain::moduleCatalog())addType_.addItem(d.id.data(),item++);addType_.setSelectedId(1);edgeGain_.setRange(0,1,.01);edgeGain_.setValue(1);edgeGain_.setTextBoxStyle(juce::Slider::TextBoxLeft,false,70,24);matrixDepth_.setRange(-1,1,.001);matrixEnabled_.setToggleState(true,juce::dontSendNotification);for(auto&s:modulatorSliders_){matrixTab_.addAndMakeVisible(s);s.setTextBoxStyle(juce::Slider::TextBoxLeft,false,70,22);}for(auto&w:lfoWaveforms_){matrixTab_.addAndMakeVisible(w);w.addItem("sine",1);w.addItem("triangle",2);}for(auto&t:macroEditors_){matrixTab_.addAndMakeVisible(t);t.setSelectAllWhenFocused(true);}
 constexpr std::array ids{"macro1","macro2","macro3","macro4","outputGain","width","masterTune","bypass"};for(std::size_t i=0;i<8;++i){addAndMakeVisible(hostSliders_[i]);hostSliders_[i].setSliderStyle(i==7?juce::Slider::LinearBar:juce::Slider::RotaryHorizontalVerticalDrag);hostSliders_[i].setTextBoxStyle(juce::Slider::TextBoxBelow,false,74,18);hostSliders_[i].setName(i<4?"Macro "+juce::String((int)i+1):juce::String(ids[i]));hostAttachments_[i]=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(o.parameters(),ids[i],hostSliders_[i]);}
 newButton_.onClick=[this]{showResult(owner_.newDocument(),"New authored patch");refresh();};resetPatchButton_.onClick=[this]{showResult(owner_.resetPatchEdits(),"Edits reset");refresh();};resetControlsButton_.onClick=[this]{owner_.resetControls();showResult({},"Controls reset");};addModuleButton_.onClick=[this]{auto i=addType_.getSelectedItemIndex();if(i>=0)addModule(domain::moduleCatalog()[(std::size_t)i].id);};removeModuleButton_.onClick=[this]{removeSelectedModule();};addEdgeButton_.onClick=[this]{addEdge(edgeSource_.getText().toStdString(),edgeDestination_.getText().toStdString(),edgeGain_.getValue());};removeEdgeButton_.onClick=[this]{removeSelectedEdge();};addRowButton_.onClick=[this]{addMatrixRow();};updateRowButton_.onClick=[this]{updateSelectedMatrixRow();};removeRowButton_.onClick=[this]{auto i=selectedRow_;showResult(owner_.editPatch([i](auto&p){if(i>=0&&i<(int)p.matrix.size())p.matrix.erase(p.matrix.begin()+i);}),"Route removed");refresh();};
 presetList_.onChange=[this]{auto i=presetList_.getSelectedItemIndex();if(i>=0&&i<(int)presets_.size()){showResult(owner_.loadStateFile(presets_[(std::size_t)i]),"Preset loaded");refresh();}};
 auto choose=[this](bool save,bool preset){chooser_=std::make_unique<juce::FileChooser>(save?"Save IUPAC patch":"Load IUPAC patch",juce::File(preset?presetDirectory().string():std::string{}),"*.iupacpatch");auto flags=save?(juce::FileBrowserComponent::saveMode|juce::FileBrowserComponent::canSelectFiles):(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles);chooser_->launchAsync(flags,[this,save,preset](const juce::FileChooser&fc){auto f=fc.getResult();if(f==juce::File{})return;if(save&&!f.hasFileExtension("iupacpatch"))f=f.withFileExtension("iupacpatch");showResult(save?owner_.saveStateFile(f.getFullPathName().toStdString()):owner_.loadStateFile(f.getFullPathName().toStdString()),save?"Patch saved":"Patch loaded");if(preset)refreshPresets();refresh();});};loadButton_.onClick=[choose]{choose(false,false);};saveButton_.onClick=[choose]{choose(true,false);};savePresetButton_.onClick=[choose]{choose(true,true);};
#if IUPAC_ENABLE_CHEMISTRY
 addAndMakeVisible(chemistryBar_);for(auto*c:std::array<juce::Component*,6>{&chemistryMode_,&chemistryInput_,&chemistryApply_,&chemistryReapply_,&chemistryDetails_,&chemistryTrace_})chemistryBar_.addAndMakeVisible(c);
 chemistryMode_.addItem("Name",1);chemistryMode_.addItem("SMILES",2);chemistryMode_.setSelectedId(1);chemistryInput_.setTextToShowWhenEmpty("Offline molecular name or SMILES",juce::Colours::grey);chemistryInput_.setName("Molecular input");chemistryTrace_.setMultiLine(true);chemistryTrace_.setReadOnly(true);chemistryTrace_.setVisible(false);chemistryTrace_.setName("Analysis SonicIntent and mapping trace");
 chemistryApply_.onClick=[this]{owner_.applyChemistry(chemistryMode_.getSelectedId()==1?chemistry::InputMode::name:chemistry::InputMode::smiles,chemistryInput_.getText().toStdString());};chemistryReapply_.onClick=[this]{showResult(owner_.reapplyChemistry(),"Reapplying chemistry");};chemistryDetails_.onClick=[this]{chemistryTrace_.setVisible(chemistryDetails_.getToggleState());resized();};
#endif
 setResizable(true,true);setResizeLimits(1000,700,1800,1200);setSize(1200,800);refresh();startTimerHz(20);
}
IupacSynthEditor::~IupacSynthEditor(){stopTimer();moduleList_.setModel(nullptr);edgeList_.setModel(nullptr);matrixList_.setModel(nullptr);}
void IupacSynthEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff15171c));}
void IupacSynthEditor::resized(){auto r=getLocalBounds().reduced(12),top=r.removeFromTop(34);for(auto*b:{&newButton_,&loadButton_,&saveButton_,&savePresetButton_,&resetPatchButton_,&resetControlsButton_})b->setBounds(top.removeFromLeft(105).reduced(2));presetList_.setBounds(top.removeFromLeft(190).reduced(2));status_.setBounds(top);
#if IUPAC_ENABLE_CHEMISTRY
 auto chemistry=r.removeFromTop(chemistryDetails_.getToggleState()?150:36);chemistryBar_.setBounds(chemistry);auto cr=chemistryBar_.getLocalBounds();auto line=cr.removeFromTop(34);chemistryMode_.setBounds(line.removeFromLeft(90).reduced(2));chemistryInput_.setBounds(line.removeFromLeft(std::max(220,getWidth()-640)).reduced(2));chemistryApply_.setBounds(line.removeFromLeft(80).reduced(2));chemistryReapply_.setBounds(line.removeFromLeft(90).reduced(2));chemistryDetails_.setBounds(line.reduced(2));chemistryTrace_.setBounds(cr.reduced(2));
#endif
 auto controls=r.removeFromTop(88);for(auto&s:hostSliders_)s.setBounds(controls.removeFromLeft(std::max(80,getWidth()/10)).reduced(3));meter_.setBounds(r.removeFromTop(24));keyboard_.setBounds(r.removeFromBottom(76));tabs_.setBounds(r);auto m=modulesTab_.getLocalBounds().reduced(8),left=m.removeFromLeft(245);addType_.setBounds(left.removeFromTop(28));addModuleButton_.setBounds(left.removeFromTop(28));removeModuleButton_.setBounds(left.removeFromTop(28));moduleList_.setBounds(left.removeFromTop(145));edgeList_.setBounds(left.removeFromTop(85));edgeSource_.setBounds(left.removeFromTop(28));edgeDestination_.setBounds(left.removeFromTop(28));edgeGain_.setBounds(left.removeFromTop(28));addEdgeButton_.setBounds(left.removeFromTop(28));removeEdgeButton_.setBounds(left.removeFromTop(28));graph_.setBounds(left);detailViewport_.setBounds(m);auto x=matrixTab_.getLocalBounds().reduced(8);matrixList_.setBounds(x.removeFromTop(160));auto row=x.removeFromTop(34);matrixSource_.setBounds(row.removeFromLeft(125).reduced(2));matrixDestination_.setBounds(row.removeFromLeft(220).reduced(2));matrixDepth_.setBounds(row.removeFromLeft(125).reduced(2));matrixEnabled_.setBounds(row.removeFromLeft(80).reduced(2));addRowButton_.setBounds(row.removeFromLeft(90).reduced(2));updateRowButton_.setBounds(row.removeFromLeft(150).reduced(2));removeRowButton_.setBounds(row.removeFromLeft(165).reduced(2));for(std::size_t i=0;i<14;++i)modulatorSliders_[i].setBounds(x.getX()+(int)(i%4)*x.getWidth()/4,x.getY()+(int)(i/4)*30,x.getWidth()/4-4,27);for(std::size_t i=0;i<2;++i)lfoWaveforms_[i].setBounds(x.getX()+(int)(i+2)*x.getWidth()/4,x.getY()+90,x.getWidth()/4-4,27);for(std::size_t i=0;i<4;++i)macroEditors_[i].setBounds(x.getX()+(int)i*x.getWidth()/4,x.getY()+125,x.getWidth()/4-4,27);}
void IupacSynthEditor::showResult(const std::string&e,juce::String ok){status_.setText(e.empty()?ok:juce::String("Rejected: ")+e,juce::dontSendNotification);status_.setColour(juce::Label::textColourId,e.empty()?juce::Colours::lightgreen:juce::Colours::orange);}
std::filesystem::path IupacSynthEditor::presetDirectory()const{auto p=juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("IUPAC Synth 2").getChildFile("Presets");p.createDirectory();return p.getFullPathName().toStdString();}
juce::String IupacSynthEditor::sourceName(int i){constexpr std::array n{"E1","E2","E3","L1","L2","Velocity","Key tracking","Pitch bend","CC1","Macro 1","Macro 2","Macro 3","Macro 4"};return n[(std::size_t)juce::jlimit(0,12,i)];}
bool IupacSynthEditor::addModule(std::string_view type){auto*d=domain::findModule(type);if(!d){showResult("unknown module type",{});return false;}auto e=owner_.editPatch([&](auto&p){p.nodes.push_back(defaultNode(uniqueId(p,d->id),*d));});showResult(e,"Module added");refresh();return e.empty();}
bool IupacSynthEditor::removeSelectedModule(){auto row=selectedModule_;auto e=owner_.editPatch([row](auto&p){if(row<0||row>=(int)p.nodes.size())return;auto id=p.nodes[(std::size_t)row].id;std::erase_if(p.edges,[&](auto&x){return x.source==id||x.destination==id;});std::erase_if(p.matrix,[&](auto&x){return x.destinationNode==id;});p.nodes.erase(p.nodes.begin()+row);});showResult(e,"Module removed");refresh();return e.empty();}
bool IupacSynthEditor::addEdge(std::string a,std::string b,double g){auto e=owner_.editPatch([&](auto&p){p.edges.push_back({std::move(a),std::move(b),g});});showResult(e,"Edge added");refresh();return e.empty();}
bool IupacSynthEditor::removeSelectedEdge(){auto row=selectedEdge_;auto e=owner_.editPatch([row](auto&p){if(row>=0&&row<(int)p.edges.size())p.edges.erase(p.edges.begin()+row);});showResult(e,"Edge removed");refresh();return e.empty();}
bool IupacSynthEditor::addMatrixRow(){auto destination=matrixDestination_.getText().toStdString();auto dot=destination.find('.');if(dot==std::string::npos){showResult("add a modulatable module first",{});return false;}auto source=(domain::ModulationSource)std::max(0,matrixSource_.getSelectedItemIndex());auto e=owner_.editPatch([&](auto&p){p.matrix.push_back({uniqueRouteId(p),matrixEnabled_.getToggleState(),source,destination.substr(0,dot),destination.substr(dot+1),matrixDepth_.getValue()});});showResult(e,"Route added");refresh();return e.empty();}
bool IupacSynthEditor::updateSelectedMatrixRow(){auto destination=matrixDestination_.getText().toStdString();auto dot=destination.find('.');auto row=selectedRow_;if(dot==std::string::npos){showResult("select a matrix destination",{});return false;}auto e=owner_.editPatch([&](auto&p){if(row>=0&&row<(int)p.matrix.size()){auto&r=p.matrix[(std::size_t)row];r.source=(domain::ModulationSource)std::max(0,matrixSource_.getSelectedItemIndex());r.destinationNode=destination.substr(0,dot);r.destinationParameter=destination.substr(dot+1);r.depth=matrixDepth_.getValue();r.enabled=matrixEnabled_.getToggleState();}});showResult(e,"Route updated");refresh();return e.empty();}
bool IupacSynthEditor::setSelectedParameter(std::string_view id,std::size_t index,double v){auto row=selectedModule_;auto e=owner_.editPatch([&](auto&p){if(row<0||row>=(int)p.nodes.size())return;auto&node=p.nodes[(std::size_t)row];for(auto&x:node.parameters)if(x.id==id&&index<x.values.size())x.values[index]=v;if(node.type==domain::ModuleType::harmonic&&(id=="tilt"||id=="inharmonicity")){double tilt=0,inharmonicity=0;for(const auto&x:node.parameters){if(x.id=="tilt")tilt=x.values[0];else if(x.id=="inharmonicity")inharmonicity=x.values[0];}(void)domain::applyHarmonicSpectrum(node,tilt,inharmonicity);}});showResult(e,"Parameter updated");return e.empty();}
void IupacSynthEditor::refresh(){refreshModules();refreshDetail();refreshGraph();refreshMatrix();refreshPresets();}
void IupacSynthEditor::refreshModules(){auto p=owner_.snapshot().editedPatch;selectedModule_=juce::jlimit(0,std::max(0,(int)p.nodes.size()-1),selectedModule_);selectedEdge_=juce::jlimit(0,std::max(0,(int)p.edges.size()-1),selectedEdge_);moduleList_.updateContent();moduleList_.selectRow(selectedModule_,false,true);edgeList_.updateContent();edgeList_.selectRow(selectedEdge_,false,true);edgeSource_.clear();edgeDestination_.clear();int i=1;for(auto&n:p.nodes){edgeSource_.addItem(n.id,i);edgeDestination_.addItem(n.id,i++);}edgeDestination_.addItem("output",i);if(edgeSource_.getNumItems())edgeSource_.setSelectedItemIndex(0);edgeDestination_.setSelectedItemIndex(edgeDestination_.getNumItems()-1);}
void IupacSynthEditor::refreshDetail(){detailLabels_.clear();detailSliders_.clear();detailChoices_.clear();arrayEditors_.clear();auto p=owner_.snapshot().editedPatch;if(p.nodes.empty()){detailContent_.setSize(500,80);return;}selectedModule_=juce::jlimit(0,(int)p.nodes.size()-1,selectedModule_);auto&n=p.nodes[(std::size_t)selectedModule_];auto&d=domain::moduleCatalog()[(std::size_t)n.type];int y=8;for(std::size_t pi=0;pi<d.parameters.size();++pi){auto&pd=d.parameters[pi];auto*l=detailLabels_.add(new juce::Label);l->setText(pd.id.data(),juce::dontSendNotification);l->setBounds(8,y,175,28);detailContent_.addAndMakeVisible(l);if(pd.kind==domain::ParameterKind::discrete){auto*c=detailChoices_.add(new juce::ComboBox);for(std::size_t i=0;i<pd.choices.size();++i)c->addItem(pd.choices[i].data(),(int)i+1);c->setSelectedItemIndex((int)n.parameters[pi].values[0]);c->onChange=[this,id=std::string(pd.id),c]{setSelectedParameter(id,0,c->getSelectedItemIndex());};c->setBounds(190,y,280,28);detailContent_.addAndMakeVisible(c);}else if(pd.arraySize){auto*t=arrayEditors_.add(new juce::TextEditor);juce::String v;for(std::size_t i=0;i<n.parameters[pi].values.size();++i){if(i)v<<", ";v<<juce::String(n.parameters[pi].values[i],4);}t->setText(v,false);t->setName(juce::String(pd.id.data())+" array");t->onReturnKey=[this,id=std::string(pd.id),t,count=pd.arraySize]{std::stringstream ss(t->getText().toStdString());std::vector<double>v;std::string x;while(std::getline(ss,x,','))try{v.push_back(std::stod(x));}catch(...){v.clear();break;}auto row=selectedModule_;auto e=owner_.editPatch([&](auto&p){if(row>=0&&row<(int)p.nodes.size())for(auto&z:p.nodes[(std::size_t)row].parameters)if(z.id==id&&v.size()==count)z.values=v;});showResult(e,"Array updated");};t->setBounds(190,y,std::max(280,detailViewport_.getWidth()-210),28);detailContent_.addAndMakeVisible(t);}else{auto*s=detailSliders_.add(new juce::Slider);s->setRange(pd.minimum,pd.maximum,(pd.maximum-pd.minimum)/10000);s->setValue(n.parameters[pi].values[0],juce::dontSendNotification);s->setTextBoxStyle(juce::Slider::TextBoxLeft,false,90,24);s->onValueChange=[this,id=std::string(pd.id),s]{setSelectedParameter(id,0,s->getValue());};s->setBounds(190,y,std::max(280,detailViewport_.getWidth()-210),28);detailContent_.addAndMakeVisible(s);}y+=34;}detailContent_.setSize(std::max(500,detailViewport_.getWidth()-16),y+8);}
void IupacSynthEditor::refreshGraph(){auto p=owner_.snapshot().editedPatch;juce::String s="Validated audio flow\n";for(auto&e:p.edges)s<<e.source<<"  --"<<juce::String(e.gain,2)<<"-->  "<<e.destination<<"\n";if(p.edges.empty())s<<"(silent: no output connection)";graph_.setText(s,juce::dontSendNotification);}
void IupacSynthEditor::refreshMatrix(){auto p=owner_.snapshot().editedPatch;matrixList_.updateContent();matrixSource_.clear();for(int i=0;i<13;++i)matrixSource_.addItem(sourceName(i),i+1);matrixSource_.setSelectedId(1);matrixDestination_.clear();int id=1;for(auto&n:p.nodes)for(auto&pd:domain::moduleCatalog()[(std::size_t)n.type].parameters)if(pd.modulatable)matrixDestination_.addItem(juce::String(n.id)+"."+pd.id.data(),id++);if(id>1)matrixDestination_.setSelectedId(1);constexpr std::array names{"E1 attack","E1 decay","E1 sustain","E1 release","E2 attack","E2 decay","E2 sustain","E2 release","E3 attack","E3 decay","E3 sustain","E3 release","L1 rate","L2 rate"};for(std::size_t i=0;i<14;++i){auto&s=modulatorSliders_[i];s.setName(names[i]);double lo=0,hi=1,value=0;if(i<12){auto&e=p.envelopes[i/4];switch(i%4){case 0:lo=.001;hi=2;value=e.attack;break;case 1:lo=.01;hi=4;value=e.decay;break;case 2:value=e.sustain;break;default:lo=.02;hi=6;value=e.release;}}else{lo=.05;hi=12;value=p.lfos[i-12].rate;}s.setRange(lo,hi,(hi-lo)/10000);s.setValue(value,juce::dontSendNotification);s.onValueChange=[this,i,&s]{auto v=s.getValue();showResult(owner_.editPatch([=](auto&p){if(i<12){auto&e=p.envelopes[i/4];switch(i%4){case 0:e.attack=v;break;case 1:e.decay=v;break;case 2:e.sustain=v;break;default:e.release=v;}}else p.lfos[i-12].rate=v;}),"Modulator updated");};}for(std::size_t i=0;i<2;++i){auto&w=lfoWaveforms_[i];w.setName("L"+juce::String((int)i+1)+" waveform");w.setSelectedItemIndex((int)p.lfos[i].waveform,juce::dontSendNotification);w.onChange=[this,i,&w]{const auto value=w.getSelectedItemIndex();showResult(owner_.editPatch([i,value](auto&patch){patch.lfos[i].waveform=(domain::LfoWaveform)value;}),"LFO waveform updated");};}for(std::size_t i=0;i<4;++i){auto&t=macroEditors_[i];t.setName("Macro "+juce::String((int)i+1)+" label and default");t.setText(juce::String(p.macros[i].label)+" | "+juce::String(p.macros[i].defaultValue,3),false);t.onReturnKey=[this,i,&t]{auto text=t.getText();auto split=text.indexOfChar('|');auto label=text.substring(0,split).trim().toStdString();auto value=text.substring(split+1).getDoubleValue();showResult(owner_.editPatch([&](auto&p){p.macros[i]={label,value};}),"Macro updated");refreshModules();};}}
void IupacSynthEditor::refreshPresets(){auto previous=presetList_.getText();presets_=owner_.presetFiles(presetDirectory());presetList_.clear();int i=1;for(auto&p:presets_)presetList_.addItem(p.stem().string(),i++);presetList_.setText(previous,juce::dontSendNotification);presetList_.setTextWhenNothingSelected("Preset library");}
void IupacSynthEditor::timerCallback(){auto s=owner_.publicationStatus();meter_.setText("Output "+juce::String(juce::Decibels::gainToDecibels(owner_.outputPeak(),-100.f),1)+" dBFS   Voices "+juce::String((int)owner_.activeVoiceCount())+"   Generation "+juce::String((juce::int64)s.audible)+(s.transitioning?" (transitioning)":" (audible)"),juce::dontSendNotification);
#if IUPAC_ENABLE_CHEMISTRY
 auto chemistry=owner_.chemistryStatus();if(chemistry.generation!=shownChemistryGeneration_||(!chemistry.busy&&status_.getText().startsWith("Chemistry"))){shownChemistryGeneration_=chemistry.generation;status_.setText("Chemistry: "+juce::String(chemistry.text),juce::dontSendNotification);status_.setColour(juce::Label::textColourId,chemistry.busy?juce::Colours::yellow:juce::Colours::lightgreen);if(chemistry.trace.isNotEmpty())chemistryTrace_.setText(chemistry.trace,false);}
#endif
}
