#include "PluginProcessor.hpp"
#include "PluginEditor.hpp"
#include <algorithm>
#include <fstream>
namespace {using namespace iupac;domain::Node makeNode(std::string id,std::string_view type){const auto*d=domain::findModule(type);domain::Node n{std::move(id),d->type,{}};for(const auto&p:d->parameters)n.parameters.push_back({std::string(p.id),std::vector<double>(p.arraySize? p.arraySize:1,p.defaultValue)});if(type=="harmonic"){n.parameters[0].values[0]=1;for(std::size_t i=0;i<16;++i)n.parameters[1].values[i]=static_cast<double>(i+1);}return n;}}
juce::AudioProcessorValueTreeState::ParameterLayout IupacSynthProcessor::parameterLayout(){using ID=juce::ParameterID;juce::AudioProcessorValueTreeState::ParameterLayout r;for(int i=1;i<=4;++i)r.add(std::make_unique<juce::AudioParameterFloat>(ID{"macro"+juce::String(i),1},"Macro "+juce::String(i),juce::NormalisableRange<float>{0,1},0));r.add(std::make_unique<juce::AudioParameterFloat>(ID{"outputGain",1},"Output gain",juce::NormalisableRange<float>{-60,6},-6));r.add(std::make_unique<juce::AudioParameterFloat>(ID{"width",1},"Width",juce::NormalisableRange<float>{0,1},.5f));r.add(std::make_unique<juce::AudioParameterFloat>(ID{"masterTune",1},"Master tune",juce::NormalisableRange<float>{-12,12},0));r.add(std::make_unique<juce::AudioParameterBool>(ID{"bypass",1},"Bypass",false));return r;}
iupac::domain::Patch IupacSynthProcessor::defaultPatch(){domain::Patch p;p.noiseSeed=1;p.nodes={makeNode("osc","harmonic")};p.edges={{"osc","output",.35}};p.macros={{{"Macro 1",0},{"Macro 2",0},{"Macro 3",0},{"Macro 4",0}}};return p;}
IupacSynthProcessor::IupacSynthProcessor():AudioProcessor(BusesProperties().withOutput("Output",juce::AudioChannelSet::stereo(),true)),document_{defaultPatch(),defaultPatch(),{},std::nullopt},parameters_(*this,nullptr,"HostControls",parameterLayout()){constexpr std::array ids{"macro1","macro2","macro3","macro4","outputGain","width","masterTune","bypass"};for(std::size_t i=0;i<ids.size();++i)parameterValues_[i]=parameters_.getRawParameterValue(ids[i]);setLatencySamples(4);
#if IUPAC_ENABLE_CHEMISTRY
 chemistry_=std::make_unique<chemistry::ExtensionCoordinator>(chemistry::locatePackagedHelper(),[this](chemistry::ApplyResult result){
  if(!result){std::scoped_lock statusLock(chemistryMutex_);if(chemistryStatus_.generation==result.generation){chemistryStatus_.busy=false;chemistryStatus_.failed=true;chemistryStatus_.stage=chemistry::Stage::idle;chemistryStatus_.text=result.error;}return;}
  auto compiled=engine::compilePatch(*result.patch);if(!compiled){std::scoped_lock statusLock(chemistryMutex_);chemistryStatus_.busy=false;chemistryStatus_.failed=true;chemistryStatus_.stage=chemistry::Stage::idle;chemistryStatus_.text=compiled.error;return;}
  juce::var discoveryRecord;{std::scoped_lock discoveryLock(discoveryMutex_);if(pendingDiscoveryGeneration_==result.generation)discoveryRecord=pendingDiscoveryRecord_.clone();}
  {std::scoped_lock documentLock(documentMutex_);if(!chemistry_||chemistry_->generation()!=result.generation)return;document_.basePatch=*result.patch;document_.editedPatch=*result.patch;document_.provenance=chemistry::makeProvenance(result);if(discoveryRecord.getDynamicObject())document_.provenance->getDynamicObject()->setProperty("discoveryRecord",discoveryRecord);publishDocument(compiled.patch);}
  auto inspection=juce::var(new juce::DynamicObject);auto*inspectionObject=inspection.getDynamicObject();inspectionObject->setProperty("analysis",result.helperResponse.getDynamicObject()->getProperty("analysis").clone());inspectionObject->setProperty("sonicIntent",chemistry::encodeSonicIntent(*result.intent));inspectionObject->setProperty("mappingTrace",result.trace.clone());
  juce::var cacheRequest(new juce::DynamicObject);auto*cache=cacheRequest.getDynamicObject();cache->setProperty("protocolVersion",chemistry::protocolVersion);cache->setProperty("requestId",juce::String("cache-")+juce::String((juce::int64)result.generation));cache->setProperty("action","cache-put");cache->setProperty("identity",juce::String(result.analysis->canonicalIsomericSmiles));juce::var versions(new juce::DynamicObject);versions.getDynamicObject()->setProperty("analysis",chemistry::analysisVersion);versions.getDynamicObject()->setProperty("projection",chemistry::sonicIntentVersion);versions.getDynamicObject()->setProperty("mapper",chemistry::mappingVersion);cache->setProperty("versions",versions);cache->setProperty("settings",juce::var(new juce::DynamicObject));cache->setProperty("state",juce::String(domain::encodeStateJson(snapshot())));auto cacheReply=chemistry::invokeProtocol(chemistry::locatePackagedHelper(),cacheRequest);
  std::scoped_lock statusLock(chemistryMutex_);chemistryStatus_.busy=false;chemistryStatus_.stage=chemistry::Stage::idle;chemistryStatus_.text="Applied "+result.analysis->canonicalIsomericSmiles+(cacheReply?" (cached)":" (cache unavailable; sound retained)");chemistryStatus_.trace=juce::JSON::toString(inspection,true);
 },[this](chemistry::Stage stage,std::uint64_t generation){
  // Worker thread. Publish the stage the popup shows while it waits (#97).
  std::scoped_lock lock(chemistryMutex_);
  if(stage==chemistry::Stage::idle){
   // Only a finished warm-up clears itself. An analysis writes its own outcome from
   // the completion callback, so idle must not overwrite that message.
   if(chemistryStatus_.stage==chemistry::Stage::warming&&chemistryStatus_.generation==generation){chemistryStatus_={false,generation,"Ready",chemistryStatus_.trace,chemistry::Stage::idle};}
   return;
  }
  // A warm-up never displaces a live analysis, and a stage belonging to a superseded
  // request is dropped.
  if(stage==chemistry::Stage::warming){if(chemistryStatus_.busy)return;}
  else if(chemistryStatus_.generation!=generation)return;
  chemistryStatus_.busy=true;chemistryStatus_.failed=false;chemistryStatus_.stage=stage;chemistryStatus_.text=std::string(chemistry::stageDescription(stage));
 });
#endif
}
void IupacSynthProcessor::prepareToPlay(double rate,int block){coordinator_.prepare(rate,static_cast<std::size_t>(std::max(1,block)));const auto c=engine::compilePatch(document_.editedPatch);if(c){std::scoped_lock lock(documentMutex_);publishDocument(c.patch);}setLatencySamples(4);}
void IupacSynthProcessor::publishDocument(const engine::CompiledPatch&patch){(void)coordinator_.publish(patch,readControls());if(!coordinator_.retryPending()&&!publishRetry_.isTimerRunning())publishRetry_.startTimer(5);}
void IupacSynthProcessor::PublishRetry::timerCallback(){std::scoped_lock lock(owner.documentMutex_);if(owner.coordinator_.retryPending())stopTimer();}
bool IupacSynthProcessor::isBusesLayoutSupported(const BusesLayout&l)const{return l.getMainOutputChannelSet()==juce::AudioChannelSet::stereo()&&l.getMainInputChannelSet().isDisabled();}
iupac::domain::HostControls IupacSynthProcessor::readControls()const noexcept{domain::HostControls c;for(std::size_t i=0;i<4;++i)c.macros[i]=parameterValues_[i]->load(std::memory_order_relaxed);c.outputGain=parameterValues_[4]->load(std::memory_order_relaxed);c.width=parameterValues_[5]->load(std::memory_order_relaxed);c.masterTune=parameterValues_[6]->load(std::memory_order_relaxed);c.bypass=parameterValues_[7]->load(std::memory_order_relaxed)>=.5f;return c;}
void IupacSynthProcessor::writeControls(const domain::HostControls&c){std::array<float,8>v{};for(std::size_t i=0;i<4;++i)v[i]=static_cast<float>(c.macros[i]);v[4]=static_cast<float>(c.outputGain);v[5]=static_cast<float>(c.width);v[6]=static_cast<float>(c.masterTune);v[7]=c.bypass?1.f:0.f;constexpr std::array ids{"macro1","macro2","macro3","macro4","outputGain","width","masterTune","bypass"};for(std::size_t i=0;i<ids.size();++i)if(auto*p=parameters_.getParameter(ids[i]))p->setValueNotifyingHost(p->convertTo0to1(v[i]));}
void IupacSynthProcessor::render(juce::AudioBuffer<float>&b,const juce::MidiBuffer&m)noexcept{juce::ScopedNoDenormals n;std::array<engine::MidiEvent,engine::maximumMidiEventsPerBlock+1>events{};std::size_t count=0;for(const auto md:m){if(count==events.size())break;const auto msg=md.getMessage();engine::MidiEvent e;e.sampleOffset=static_cast<std::uint32_t>(std::max(0,md.samplePosition));e.channel=static_cast<std::uint8_t>(std::max(1,msg.getChannel()));if(msg.isNoteOn()){e.type=engine::MidiEventType::noteOn;e.data1=static_cast<std::uint8_t>(msg.getNoteNumber());e.data2=static_cast<std::uint8_t>(std::clamp(juce::roundToInt(msg.getFloatVelocity()*127),0,127));}else if(msg.isNoteOff()){e.type=engine::MidiEventType::noteOff;e.data1=static_cast<std::uint8_t>(msg.getNoteNumber());}else if(msg.isPitchWheel()){e.type=engine::MidiEventType::pitchBend;e.bend=static_cast<std::uint16_t>(msg.getPitchWheelValue());}else if(msg.isController()){e.type=engine::MidiEventType::controlChange;e.data1=static_cast<std::uint8_t>(msg.getControllerNumber());e.data2=static_cast<std::uint8_t>(msg.getControllerValue());}else continue;events[count++]=e;}// ARCHITECTURE "Tempo sync": the host playhead when there is one, the documented 120 BPM fallback
 // in Standalone or in a host that reports no position. Reading the playhead allocates nothing.
 double tempo=iupac::engine::fallbackTempoBpm;if(auto*playHead=getPlayHead())if(const auto position=playHead->getPosition())if(const auto bpm=position->getBpm())tempo=*bpm;
 coordinator_.setTempo(tempo);coordinator_.setAudioControls(readControls());coordinator_.render({b.getWritePointer(0),static_cast<std::size_t>(b.getNumSamples())},{b.getWritePointer(1),static_cast<std::size_t>(b.getNumSamples())},{events.data(),count});float peak=0;for(int c=0;c<b.getNumChannels();++c)peak=std::max(peak,b.getMagnitude(c,0,b.getNumSamples()));outputPeak_.store(peak,std::memory_order_relaxed);}
void IupacSynthProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&m){keyboardState_.processNextMidiBuffer(m,0,b.getNumSamples(),true);render(b,m);}void IupacSynthProcessor::processBlock(juce::AudioBuffer<double>&b,juce::MidiBuffer&){juce::ScopedNoDenormals n;b.clear();}juce::AudioProcessorEditor*IupacSynthProcessor::createEditor(){
#if IUPAC_ENABLE_CHEMISTRY
 prewarmChemistry();
#endif
 return new IupacSynthEditor(*this);}
iupac::domain::State IupacSynthProcessor::snapshot()const{std::scoped_lock lock(documentMutex_);auto r=document_;r.controls=readControls();return r;}
std::string IupacSynthProcessor::loadState(domain::State s){auto c=engine::compilePatch(s.editedPatch);if(!c)return c.error;
#if IUPAC_ENABLE_CHEMISTRY
 cancelChemistry();
#endif
 writeControls(s.controls);{std::scoped_lock lock(documentMutex_);document_=std::move(s);publishDocument(c.patch);}return{};}
std::string IupacSynthProcessor::newDocument(){domain::State s{defaultPatch(),defaultPatch(),{},std::nullopt};return loadState(std::move(s));}std::string IupacSynthProcessor::resetPatchEdits(){auto s=snapshot();s.editedPatch=s.basePatch;return loadState(std::move(s));}void IupacSynthProcessor::resetControls(){auto s=snapshot();for(std::size_t i=0;i<4;++i)s.controls.macros[i]=s.editedPatch.macros[i].defaultValue;s.controls.outputGain=-6;s.controls.width=.5;s.controls.masterTune=0;s.controls.bypass=false;writeControls(s.controls);}
std::string IupacSynthProcessor::editPatch(const std::function<void(domain::Patch&)>& edit){auto s=snapshot();edit(s.editedPatch);if(auto error=domain::validate(s.editedPatch);!error.empty())return error;s.provenance.reset();return loadState(std::move(s));}
#if IUPAC_ENABLE_CHEMISTRY
std::uint64_t IupacSynthProcessor::applyChemistry(chemistry::InputMode mode,std::string input){// A warm-up already in flight is doing this request's first-execution work, so say so
// rather than claiming the molecule is being analysed; the worker republishes the real
// stage as soon as it starts (#97).
const auto stage=chemistry_->stage()==chemistry::Stage::warming?chemistry::Stage::warming:chemistry::Stage::analysing;auto generation=chemistry_->apply(mode,std::move(input));std::scoped_lock lock(chemistryMutex_);chemistryStatus_={true,generation,std::string(chemistry::stageDescription(stage)),{},stage,false};return generation;}
// Called when an editor opens (#97): the private payload costs 13-30 s the first
// time macOS executes it after an install, and that cost belongs in the background
// while the user is still looking at the synth, never on the message thread and
// never on the first Apply. At most one warm-up runs per processor.
void IupacSynthProcessor::prewarmChemistry(){if(chemistry_)chemistry_->prewarm();}
void IupacSynthProcessor::cancelChemistry(){if(!chemistry_)return;chemistry_->cancel();std::scoped_lock lock(chemistryMutex_);chemistryStatus_.busy=false;chemistryStatus_.failed=true;chemistryStatus_.generation=chemistry_->generation();chemistryStatus_.text="Cancelled";chemistryStatus_.stage=chemistry::Stage::idle;}
IupacSynthProcessor::ChemistryStatus IupacSynthProcessor::chemistryStatus()const{std::scoped_lock lock(chemistryMutex_);return chemistryStatus_;}
std::string IupacSynthProcessor::reapplyChemistry(){auto state=snapshot();if(!state.provenance)return "no stored chemistry provenance";auto*object=state.provenance->getDynamicObject();if(!object||object->getProperty("kind").toString()!="chemistry-generation-v1")return "stored provenance cannot be reapplied";auto mode=object->getProperty("mode").toString()=="name"?chemistry::InputMode::name:chemistry::InputMode::smiles;auto input=object->getProperty("input").toString().toStdString();applyChemistry(mode,std::move(input));return{};}
std::uint64_t IupacSynthProcessor::searchDiscovery(std::string query,bool prefix){const auto generation=discoveryGeneration_.fetch_add(1)+1;if(discoveryWorker_.joinable()){discoveryWorker_.request_stop();discoveryWorker_.join();}{std::scoped_lock lock(discoveryMutex_);discoveryStatus_={true,generation,"Searching offline index...",{}};}discoveryWorker_=std::jthread([this,generation,query=std::move(query),prefix](std::stop_token stop){juce::var request(new juce::DynamicObject);auto*o=request.getDynamicObject();o->setProperty("protocolVersion",chemistry::protocolVersion);o->setProperty("requestId",juce::String((juce::int64)generation));o->setProperty("action","discover");o->setProperty("query",juce::String(query));o->setProperty("prefix",prefix);o->setProperty("limit",32);auto reply=chemistry::invokeProtocol(chemistry::locatePackagedHelper(),request,stop);if(stop.stop_requested()||discoveryGeneration_.load()!=generation)return;std::scoped_lock lock(discoveryMutex_);discoveryStatus_.busy=false;if(!reply){discoveryStatus_.text=reply.error;return;}discoveryStatus_.result=reply.response.getProperty("discovery",{}).clone();auto candidates=discoveryStatus_.result.getProperty("candidates",{});discoveryStatus_.text=std::to_string(candidates.isArray()?candidates.getArray()->size():0)+" local candidates";});return generation;}
std::uint64_t IupacSynthProcessor::inspectGeneratedCache(){const auto generation=discoveryGeneration_.fetch_add(1)+1;if(discoveryWorker_.joinable()){discoveryWorker_.request_stop();discoveryWorker_.join();}{std::scoped_lock lock(discoveryMutex_);discoveryStatus_={true,generation,"Inspecting generated cache...",{}};}discoveryWorker_=std::jthread([this,generation](std::stop_token stop){juce::var request(new juce::DynamicObject);auto*o=request.getDynamicObject();o->setProperty("protocolVersion",chemistry::protocolVersion);o->setProperty("requestId",juce::String((juce::int64)generation));o->setProperty("action","cache-inspect");auto reply=chemistry::invokeProtocol(chemistry::locatePackagedHelper(),request,stop);if(stop.stop_requested()||discoveryGeneration_.load()!=generation)return;std::scoped_lock lock(discoveryMutex_);discoveryStatus_.busy=false;if(!reply){discoveryStatus_.text=reply.error;return;}discoveryStatus_.result=reply.response.getProperty("cache",{}).clone();discoveryStatus_.text=std::to_string(discoveryStatus_.result.isArray()?discoveryStatus_.result.getArray()->size():0)+" cached generated sounds";});return generation;}
std::string IupacSynthProcessor::clearGeneratedCache(){juce::var request(new juce::DynamicObject);auto*o=request.getDynamicObject();o->setProperty("protocolVersion",chemistry::protocolVersion);o->setProperty("requestId","clear");o->setProperty("action","cache-clear");auto reply=chemistry::invokeProtocol(chemistry::locatePackagedHelper(),request);return reply?std::string{}:reply.error;}
std::string IupacSynthProcessor::applyDiscovery(const juce::var& record){auto*o=record.getDynamicObject();if(!o)return "select a discovery candidate or cached result";auto path=o->getProperty("path").toString().toStdString();if(!path.empty())return loadStateFile(path);if(o->getProperty("validationStatus").toString()!="validated")return "selected discovery record has conflicting or unvalidated structure";auto structure=o->getProperty("canonicalIsomericSmiles").toString().toStdString();if(structure.empty())return "selected discovery record has no validated structure";auto generation=applyChemistry(chemistry::InputMode::smiles,structure);{std::scoped_lock lock(discoveryMutex_);pendingDiscoveryRecord_=record.clone();pendingDiscoveryGeneration_=generation;}return{};}
void IupacSynthProcessor::cancelDiscovery(){discoveryGeneration_.fetch_add(1);if(discoveryWorker_.joinable()){discoveryWorker_.request_stop();discoveryWorker_.join();}std::scoped_lock lock(discoveryMutex_);discoveryStatus_.busy=false;discoveryStatus_.generation=discoveryGeneration_.load();discoveryStatus_.text="Cancelled";}
IupacSynthProcessor::DiscoveryStatus IupacSynthProcessor::discoveryStatus()const{std::scoped_lock lock(discoveryMutex_);return discoveryStatus_;}
#endif
std::string IupacSynthProcessor::saveStateFile(const std::filesystem::path& path)const{const auto text=domain::encodeStateJson(snapshot(),true);std::ofstream out(path,std::ios::binary|std::ios::trunc);if(!out)return "could not open state file for writing";out.write(text.data(),static_cast<std::streamsize>(text.size()));return out?std::string{}:"could not write state file";}
std::string IupacSynthProcessor::loadStateFile(const std::filesystem::path& path){std::error_code ec;const auto size=std::filesystem::file_size(path,ec);if(ec||size>domain::maximumDocumentBytes)return "state file missing or too large";std::ifstream in(path,std::ios::binary);std::string text((std::istreambuf_iterator<char>(in)),{});auto decoded=domain::decodeStateJson(text);return decoded?loadState(std::move(*decoded.value)):decoded.error;}
std::vector<std::filesystem::path> IupacSynthProcessor::presetFiles(const std::filesystem::path& directory)const{std::vector<std::filesystem::path> files;std::error_code ec;for(std::filesystem::directory_iterator it(directory,ec),end;!ec&&it!=end;it.increment(ec))if(it->is_regular_file(ec)&&it->path().extension()==".iupacpatch")files.push_back(it->path());std::ranges::sort(files);return files;}
void IupacSynthProcessor::getStateInformation(juce::MemoryBlock&d){const auto e=domain::encodeStateJson(snapshot());d.replaceAll(e.data(),e.size());}void IupacSynthProcessor::setStateInformation(const void*data,int size){if(!data||size<0||static_cast<std::size_t>(size)>domain::maximumDocumentBytes)return;auto d=domain::decodeStateJson({static_cast<const char*>(data),static_cast<std::size_t>(size)});if(d)(void)loadState(std::move(*d.value));}
juce::AudioProcessor*JUCE_CALLTYPE createPluginFilter(){return new IupacSynthProcessor();}
