#include "iupac/engine/Engine.hpp"
#include "iupac/engine/PatchCoordinator.hpp"
#include "MaximalPatch.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <iostream>
#include <numeric>
#include <span>
#include <vector>

namespace {
using namespace iupac;
domain::Node defaults(std::string id,std::string_view type){auto*d=domain::findModule(type);domain::Node n{std::move(id),d->type,{}};for(auto&p:d->parameters)n.parameters.push_back({std::string(p.id),std::vector<double>(p.arraySize?p.arraySize:1,p.defaultValue)});if(type=="harmonic"){n.parameters[0].values[0]=1;for(std::size_t i=0;i<16;++i)n.parameters[1].values[i]=static_cast<double>(i+1);}return n;}
domain::Patch graphPatch(bool serial=true){domain::Patch p;p.noiseSeed=77;p.nodes={defaults("a","harmonic"),defaults("b","filter"),defaults("c","mixer"),defaults("unused","noise")};p.edges=serial?std::vector<domain::AudioEdge>{{"a","b",1},{"b","c",1},{"c","output",1}}:std::vector<domain::AudioEdge>{{"a","b",1},{"b","c",.5},{"a","c",.5},{"c","output",1}};p.matrix={{"m1",true,domain::ModulationSource::l1,"b","cutoff",.8},{"m2",true,domain::ModulationSource::velocity,"c","pan",.5},{"m3",true,domain::ModulationSource::macro1,"c","level",-.5}};p.macros[0]={"Shape",.2};return p;}
bool expect(bool v,const char*m){if(!v)std::cerr<<"engine test failed: "<<m<<'\n';return v;}
float energy(const std::vector<float>&v){return std::inner_product(v.begin(),v.end(),v.begin(),0.f);}
float targetValue(const engine::ModuleValues&v,engine::ParameterTarget t){switch(t){case engine::ParameterTarget::carrierRatio:return v.carrierRatio;case engine::ParameterTarget::modulatorRatio:return v.modulatorRatio;case engine::ParameterTarget::index:return v.index;case engine::ParameterTarget::burstMilliseconds:return v.burstMilliseconds;case engine::ParameterTarget::tuneRatio:return v.tuneRatio;case engine::ParameterTarget::combFeedback:return v.combFeedback;case engine::ParameterTarget::modalQ:return v.modalQ;case engine::ParameterTarget::cutoff:return v.cutoff;case engine::ParameterTarget::q:return v.q;case engine::ParameterTarget::drive:return v.drive;case engine::ParameterTarget::wet:return v.wet;case engine::ParameterTarget::level:return v.level;case engine::ParameterTarget::pan:return v.pan;case engine::ParameterTarget::outputLevel:return v.outputLevel;}return 0;}
void setTarget(engine::ModuleValues&v,engine::ParameterTarget t,float x){switch(t){case engine::ParameterTarget::carrierRatio:v.carrierRatio=x;break;case engine::ParameterTarget::modulatorRatio:v.modulatorRatio=x;break;case engine::ParameterTarget::index:v.index=x;break;case engine::ParameterTarget::burstMilliseconds:v.burstMilliseconds=x;break;case engine::ParameterTarget::tuneRatio:v.tuneRatio=x;break;case engine::ParameterTarget::combFeedback:v.combFeedback=x;break;case engine::ParameterTarget::modalQ:v.modalQ=x;break;case engine::ParameterTarget::cutoff:v.cutoff=x;break;case engine::ParameterTarget::q:v.q=x;break;case engine::ParameterTarget::drive:v.drive=x;break;case engine::ParameterTarget::wet:v.wet=x;break;case engine::ParameterTarget::level:v.level=x;break;case engine::ParameterTarget::pan:v.pan=x;break;case engine::ParameterTarget::outputLevel:v.outputLevel=x;break;}}
std::vector<float> render(const engine::CompiledPatch&p,std::size_t block,domain::HostControls controls={},double tempo=engine::fallbackTempoBpm,std::uint8_t velocity=100,std::size_t samples=2048){engine::Engine e;e.prepare(48000,block);e.setTempo(tempo);e.setPatch(p);e.setControls(controls);std::vector<float>l(samples),r(samples);std::array events{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,velocity,8192},engine::MidiEvent{1500,engine::MidiEventType::noteOff,1,60,0,8192}};e.render(l,r,events);return l;}
float distance(const std::vector<float>&a,const std::vector<float>&b){float d=0;for(std::size_t i=0;i<std::min(a.size(),b.size());++i)d+=std::abs(a[i]-b[i]);return d;}
// D8 effects tail (#123). A source into a mixer, the mixer into the ordered effects nodes, the last
// effect into OUT. `order` names the effects types in the order they should be chained.
domain::Patch tailPatch(std::vector<std::string_view> order){domain::Patch p;p.noiseSeed=91;p.nodes={defaults("a","harmonic"),defaults("m","mixer")};p.edges={{"a","m",1}};
 std::string previous="m";for(std::size_t i=0;i<order.size();++i){auto id="x"+std::to_string(i);p.nodes.push_back(defaults(id,order[i]));p.edges.push_back({previous,id,1});previous=id;}
 p.edges.push_back({previous,"output",1});return p;}
domain::Node*nodeNamed(domain::Patch&p,std::string_view id){for(auto&n:p.nodes)if(n.id==id)return &n;return nullptr;}
void setParameter(domain::Patch&p,std::string_view id,std::string_view parameter,double value){if(auto*n=nodeNamed(p,id))for(auto&v:n->parameters)if(v.id==parameter)v.values[0]=value;}
}

bool runEngineTests(){bool ok=true;auto patch=graphPatch();auto compiled=engine::compilePatch(patch);ok&=expect(static_cast<bool>(compiled),"valid graph compiles");ok&=expect(compiled.patch.nodeCount==3,"disconnected node pruned");ok&=expect(compiled.patch.nodes[0].type==domain::ModuleType::harmonic&&compiled.patch.nodes[2].type==domain::ModuleType::mixer,"stable topological order");ok&=expect(compiled.patch.rowCount==3,"enabled live rows resolved");auto signal=render(compiled.patch,128);ok&=expect(energy(signal)>1e-4f,"compiled graph renders audio");ok&=expect(std::ranges::all_of(signal,[](float x){return std::isfinite(x)&&std::abs(x)<=.8912511f;}),"stereo safety guard bounds output");
 auto parallel=engine::compilePatch(graphPatch(false));auto changed=render(parallel.patch,128);float delta=0;for(std::size_t i=0;i<signal.size();++i)delta+=std::abs(signal[i]-changed[i]);ok&=expect(delta>1.f,"graph rewiring changes production render");
 auto allSources=graphPatch();allSources.matrix.clear();for(std::size_t i=0;i<=static_cast<std::size_t>(domain::ModulationSource::macro4);++i)allSources.matrix.push_back({"source-"+std::to_string(i),true,static_cast<domain::ModulationSource>(i),"b","cutoff",.1});auto sourceCompile=engine::compilePatch(allSources);ok&=expect(static_cast<bool>(sourceCompile)&&sourceCompile.patch.rowCount==13,"every matrix source resolves");
 auto noRows=graphPatch();noRows.matrix.clear();auto base=engine::compilePatch(noRows);domain::HostControls controls;controls.macros[0]=1;auto modulated=render(compiled.patch,128,controls),unmodulated=render(base.patch,128,controls);delta=0;for(std::size_t i=0;i<signal.size();++i)delta+=std::abs(modulated[i]-unmodulated[i]);ok&=expect(delta>.1f,"matrix rows change production render");
 for(std::size_t sourceIndex=0;sourceIndex<engine::ModulationInputs{}.size();++sourceIndex)for(std::size_t targetIndex=0;targetIndex<=static_cast<std::size_t>(engine::ParameterTarget::outputLevel);++targetIndex){const auto target=static_cast<engine::ParameterTarget>(targetIndex);engine::CompiledPatch sum;sum.rowCount=2;sum.rows[0]={static_cast<domain::ModulationSource>(sourceIndex),0,target,.5f,0,1,domain::ParameterScale::linear};sum.rows[1]={static_cast<domain::ModulationSource>(sourceIndex),0,target,-.5f,0,1,domain::ParameterScale::linear};engine::ModuleValues values;setTarget(values,target,.9f);engine::ModulationInputs inputs{};inputs[sourceIndex]=1;auto forward=engine::applyModulation(sum,0,values,inputs);std::swap(sum.rows[0],sum.rows[1]);auto reverse=engine::applyModulation(sum,0,values,inputs);ok&=expect(std::abs(targetValue(forward,target)-.9f)<1e-6f&&std::abs(targetValue(reverse,target)-.9f)<1e-6f,"matrix sums once independent of row order for every source and destination");}
 auto reference=render(compiled.patch,1);float maximumDifference=0;for(auto block:{64U,127U,512U,4096U}){auto candidate=render(compiled.patch,block);for(std::size_t i=0;i<reference.size();++i)maximumDifference=std::max(maximumDifference,std::abs(reference[i]-candidate[i]));}ok&=expect(maximumDifference<=1e-6f,"static render is block invariant at gate sizes");ok&=expect(reference==render(compiled.patch,1),"fresh engine render is deterministic");
 ok&=expect(std::abs(engine::filterCutoffCeiling(44100)-17640.f)<1e-6f,"filter cutoff inspection uses the output-rate ceiling");
 domain::Patch onsetPatch;onsetPatch.nodes={defaults("noise","noise")};onsetPatch.edges={{"noise","output",1}};auto onsetCompiled=engine::compilePatch(onsetPatch);engine::Engine onsetEngine;onsetEngine.prepare(48000,512);onsetEngine.setPatch(onsetCompiled.patch);std::array<float,512>onsetL{},onsetR{};std::array onsetNote{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,127,8192}};onsetEngine.render(onsetL,onsetR,onsetNote);auto onset=std::ranges::find_if(onsetL,[](float x){return std::abs(x)>1e-12f;});ok&=expect(onset!=onsetL.end()&&onsetEngine.latencySamples()==4,"integer-compensated oversampling reports the realized production configuration");
 engine::Engine voices;voices.prepare(48000,64);voices.setPatch(compiled.patch);std::vector<engine::MidiEvent> many;for(int i=0;i<20;++i)many.push_back({0,engine::MidiEventType::noteOn,static_cast<std::uint8_t>(i%2+1),static_cast<std::uint8_t>(40+i),100,8192});std::array<float,64>l{},r{};voices.render(l,r,many);ok&=expect(voices.activeVoiceCount()==16,"voice scheduling remains bounded");std::array controllerEvents{engine::MidiEvent{0,engine::MidiEventType::pitchBend,1,0,0,16383},engine::MidiEvent{0,engine::MidiEventType::controlChange,1,1,127,8192},engine::MidiEvent{0,engine::MidiEventType::controlChange,1,64,127,8192},engine::MidiEvent{1,engine::MidiEventType::noteOff,1,40,0,8192},engine::MidiEvent{2,engine::MidiEventType::controlChange,1,64,0,8192},engine::MidiEvent{3,engine::MidiEventType::controlChange,1,120,0,8192}};voices.render(l,r,controllerEvents);for(int i=0;i<8;++i)voices.render(l,r);ok&=expect(voices.activeVoiceCount()<16,"controllers and bounded channel all-sound-off fade are handled");ok&=expect(voices.latencySamples()>0,"integer oversampling latency reported");
 std::vector<engine::MidiEvent> overflow(engine::maximumMidiEventsPerBlock+1,{0,engine::MidiEventType::controlChange,1,1,64,8192});voices.render(l,r,overflow);for(int i=0;i<8;++i)voices.render(l,r);ok&=expect(voices.midiOverflowCount()==1&&voices.activeVoiceCount()==0,"MIDI overflow is counted and silenced with a bounded fade");auto overflowBefore=voices.midiOverflowCount();std::span<float> empty;std::array zeroEvent{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,100,8192}};voices.render(empty,empty,zeroEvent);ok&=expect(voices.midiOverflowCount()==overflowBefore&&voices.activeVoiceCount()==0,"zero host blocks do not consume MIDI or alter voices");
 std::array repeated{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,100,8192},engine::MidiEvent{1,engine::MidiEventType::noteOn,1,60,80,8192},engine::MidiEvent{2,engine::MidiEventType::noteOff,1,60,0,8192},engine::MidiEvent{3,engine::MidiEventType::controlChange,1,64,127,8192},engine::MidiEvent{4,engine::MidiEventType::noteOff,1,60,0,8192}};voices.render(l,r,repeated);ok&=expect(voices.activeVoiceCount()==2,"repeated notes release oldest while sustain retains the second voice");std::array sustainUp{engine::MidiEvent{0,engine::MidiEventType::controlChange,1,64,0,8192}};voices.render(l,r,sustainUp);ok&=expect(voices.activeVoiceCount()==2,"sustain release enters bounded envelope release");voices.reset();voices.setPatch(compiled.patch);std::array oneNote{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,100,8192}};voices.render(l,r,oneNote);auto first=l;voices.reset();voices.render(l,r,oneNote);ok&=expect(first==l,"fresh voice reuse clears DSP and modulator history deterministically");std::array invalid{engine::MidiEvent{0,engine::MidiEventType::noteOn,0,60,100,8192},engine::MidiEvent{0,engine::MidiEventType::noteOn,1,128,100,8192}};voices.reset();voices.render(l,r,invalid);ok&=expect(voices.activeVoiceCount()==0,"invalid MIDI fields are ignored safely");
 auto maximal=engine::compilePatch(iupac::testing::maximalPatch());ok&=expect(static_cast<bool>(maximal)&&maximal.patch.nodeCount==domain::maximumNodes&&maximal.patch.edgeCount==domain::maximumEdges&&maximal.patch.rowCount==domain::maximumMatrixRows,"maximal patch compiles with every node, edge and row live");ok&=expect(std::ranges::count_if(std::span(maximal.patch.edges.data(),maximal.patch.edgeCount),[](const engine::CompiledEdge&e){return e.toOutput;})==3&&maximal.patch.nodes[maximal.patch.nodeCount-1].type==domain::ModuleType::width,"maximal patch keeps all three output edges and ends at the width slot");
 ok&=expect(maximal.patch.tailStart==12&&std::ranges::all_of(std::span(maximal.patch.nodes.data()+maximal.patch.tailStart,maximal.patch.nodeCount-maximal.patch.tailStart),[](const engine::CompiledNode&n){return domain::moduleCatalog()[static_cast<std::size_t>(n.type)].effects;})&&std::ranges::none_of(std::span(maximal.patch.nodes.data(),maximal.patch.tailStart),[](const engine::CompiledNode&n){return domain::moduleCatalog()[static_cast<std::size_t>(n.type)].effects;}),"the compiler places the four effects slots last, in the global tail");auto maximalSignal=render(maximal.patch,128);ok&=expect(energy(maximalSignal)>1e-4f&&std::ranges::all_of(maximalSignal,[](float x){return std::isfinite(x)&&std::abs(x)<=.8912511f;}),"maximal patch renders bounded audio");
 domain::Patch silent;auto cs=engine::compilePatch(silent);ok&=expect(static_cast<bool>(cs)&&cs.patch.nodeCount==0,"intentional silent patch compiles");
 engine::PatchCoordinator coordinator;coordinator.prepare(48000,128);auto firstGeneration=coordinator.publish(compiled.patch,{});std::array<float,128>txL{},txR{};coordinator.render(txL,txR);ok&=expect(coordinator.status().accepted==firstGeneration&&coordinator.activeBanks()==2,"structural publication begins a bounded two-bank transition");for(int i=0;i<8;++i)coordinator.render(txL,txR);ok&=expect(!coordinator.status().transitioning&&coordinator.status().audible==firstGeneration,"structural transition reaches its audible generation in bounded time");
 std::array heldNote{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,60,100,8192}};coordinator.render(txL,txR,heldNote);auto scalar=compiled.patch;scalar.nodes[0].values.outputLevel=.25f;auto scalarGeneration=coordinator.publish(scalar,{});coordinator.render(txL,txR);ok&=expect(coordinator.activeBanks()==1&&!coordinator.status().transitioning&&coordinator.status().audible==scalarGeneration,"scalar edits preserve held voices without a bank transition");
 auto structuralPatch=engine::compilePatch(graphPatch(false)).patch;auto structuralGeneration=coordinator.publish(structuralPatch,{});coordinator.render(txL,txR);ok&=expect(coordinator.status().accepted==structuralGeneration&&coordinator.activeBanks()==2,"topology edit uses exactly two prepared banks");for(int i=0;i<8;++i)coordinator.render(txL,txR);ok&=expect(coordinator.status().audible==structuralGeneration,"held-note structural replacement completes audibly");
 std::uint64_t newest=0;for(int i=0;i<1000;++i){auto p=scalar;p.nodes[0].values.outputLevel=static_cast<float>(i%100)/100;newest=coordinator.publish(p,{});}coordinator.render(txL,txR);ok&=expect(coordinator.retryPending(),"producer retries its retained latest request after saturation");coordinator.render(txL,txR);ok&=expect(coordinator.status().accepted==newest,"saturated bounded queue retains and retries the newest desired generation");auto stale=coordinator.currentGeneration();coordinator.invalidateAsyncAuthors();ok&=expect(!coordinator.publishIfCurrent(stale,compiled.patch,{}),"manual invalidation prevents stale asynchronous publication");
 {// #68: block-rate effective-parameter publication through the production coordinator path.
  auto lfoPatch=graphPatch();lfoPatch.matrix={{"m1",true,domain::ModulationSource::l1,"b","cutoff",1}};lfoPatch.lfos[0].rate=8;auto lfoCompiled=engine::compilePatch(lfoPatch);std::size_t filterSlot=0;for(std::size_t n=0;n<lfoCompiled.patch.nodeCount;++n)if(lfoCompiled.patch.nodes[n].type==domain::ModuleType::filter)filterSlot=n;const auto cutoffIndex=static_cast<std::size_t>(engine::ParameterTarget::cutoff);const auto*cutoffDescriptor=domain::findParameter(domain::moduleCatalog()[static_cast<std::size_t>(domain::ModuleType::filter)],"cutoff");const float baseCutoff=static_cast<float>(cutoffDescriptor->normalize(lfoCompiled.patch.nodes[filterSlot].values.cutoff));
  engine::PatchCoordinator effective;effective.prepare(48000,128);(void)effective.publish(lfoCompiled.patch,{});std::array<float,128>eL{},eR{};for(int i=0;i<12;++i)effective.render(eL,eR);auto idle=effective.effectiveValues();ok&=expect(idle.nodeCount==lfoCompiled.patch.nodeCount&&idle.nodeIds[filterSlot]==lfoCompiled.patch.nodes[filterSlot].idHash&&std::abs(idle.values[filterSlot][cutoffIndex]-baseCutoff)<1e-6f,"effective value equals the base with no active voice");ok&=expect(idle.values[filterSlot][static_cast<std::size_t>(engine::ParameterTarget::index)]==-1.f&&idle.values[domain::maximumNodes-1][cutoffIndex]==-1.f&&idle.nodeIds[domain::maximumNodes-1]==0,"ineligible parameters and empty slots publish -1");
  effective.render(eL,eR,heldNote);float lo=1,hi=0;bool inRange=true;for(int i=0;i<40;++i){effective.render(eL,eR);const float v=effective.effectiveValues().values[filterSlot][cutoffIndex];inRange&=v>=0.f&&v<=1.f;lo=std::min(lo,v);hi=std::max(hi,v);}ok&=expect(inRange&&lo<baseCutoff&&hi>baseCutoff&&hi-lo>.2f,"LFO->cutoff at depth 1 publishes an oscillating clamped normalized value around the base");
  auto velocityPatch=graphPatch();velocityPatch.matrix={{"m1",true,domain::ModulationSource::velocity,"b","cutoff",.5},{"m2",true,domain::ModulationSource::keyTracking,"b","cutoff",-.25}};auto velocityCompiled=engine::compilePatch(velocityPatch);engine::PatchCoordinator held;held.prepare(48000,128);(void)held.publish(velocityCompiled.patch,{});for(int i=0;i<12;++i)held.render(eL,eR);std::array velocityNote{engine::MidiEvent{0,engine::MidiEventType::noteOn,1,72,100,8192}};held.render(eL,eR,velocityNote);held.render(eL,eR);engine::ModulationInputs inputs{};inputs[static_cast<std::size_t>(domain::ModulationSource::velocity)]=100/127.f;inputs[static_cast<std::size_t>(domain::ModulationSource::keyTracking)]=(72-60)/36.f;const auto expected=engine::applyModulation(velocityCompiled.patch,filterSlot,velocityCompiled.patch.nodes[filterSlot].values,inputs);const float expectedNormalized=static_cast<float>(cutoffDescriptor->normalize(expected.cutoff));const float published=held.effectiveValues().values[filterSlot][cutoffIndex];ok&=expect(std::abs(published-expectedNormalized)<1e-5f&&std::abs(published-baseCutoff)>.05f,"published cutoff matches the production matrix summation for a held voice");
  auto disabledPatch=velocityPatch;for(auto&row:disabledPatch.matrix)row.enabled=false;auto disabledCompiled=engine::compilePatch(disabledPatch);(void)held.publish(disabledCompiled.patch,{});for(int i=0;i<12;++i)held.render(eL,eR);ok&=expect(held.activeVoiceCount()==1&&std::abs(held.effectiveValues().values[filterSlot][cutoffIndex]-baseCutoff)<1e-6f,"disabled rows publish the base while the voice stays held");
  std::array releaseNote{engine::MidiEvent{0,engine::MidiEventType::controlChange,1,120,0,8192}};held.render(eL,eR,releaseNote);for(int i=0;i<8;++i)held.render(eL,eR);ok&=expect(held.activeVoiceCount()==0&&std::abs(held.effectiveValues().values[filterSlot][cutoffIndex]-baseCutoff)<1e-6f,"effective value returns to the base after the last voice retires");}
 {// #123: the post-mixer global effects tail with the chorus and the tempo-synced stereo delay.
  const auto dry=render(engine::compilePatch(tailPatch({})).patch,128);
  // A wet-dry `mix` of 0 makes either effect a literal straight wire, which is the same signal a
  // patch with no effects node at all renders: the tail is inside the graph, not an always-on stage.
  auto bypassed=tailPatch({"chorus","delay"});setParameter(bypassed,"x0","mix",0);setParameter(bypassed,"x1","mix",0);
  ok&=expect(distance(dry,render(engine::compilePatch(bypassed).patch,128))==0.f,"an effects tail at mix 0 renders the identical samples as a patch with no effects node");
  auto wet=tailPatch({"chorus","delay"});setParameter(wet,"x0","mix",.6);setParameter(wet,"x1","mix",.6);setParameter(wet,"x1","timeMs",5);
  const auto wetSignal=render(engine::compilePatch(wet).patch,128);
  ok&=expect(distance(dry,wetSignal)>.5f&&std::ranges::all_of(wetSignal,[](float x){return std::isfinite(x)&&std::abs(x)<=.8912511f;}),"the chorus and delay are audible and stay inside the output guard");
  // Ordering is the compiled tail partition, so swapping the two effects is a different render.
  auto swapped=tailPatch({"delay","chorus"});setParameter(swapped,"x0","mix",.6);setParameter(swapped,"x0","timeMs",5);setParameter(swapped,"x1","mix",.6);
  ok&=expect(distance(wetSignal,render(engine::compilePatch(swapped).patch,128))>.5f,"the tail runs the effects in the compiled order, so chorus-then-delay differs from delay-then-chorus");
  // The tail input carries each voice's contribution after E1 and velocity, so a quieter note makes
  // a quieter tail.
  ok&=expect(distance(render(engine::compilePatch(wet).patch,128,{},engine::fallbackTempoBpm,40),wetSignal)>.1f,"velocity gates a voice's contribution to the tail");
  // Tempo sync. `1/8` is half a quarter-note beat, which at the 120 BPM fallback is exactly 250 ms,
  // and the same division at 60 BPM is exactly 500 ms — both identical to the free time that says so.
  auto synced=tailPatch({"delay"});setParameter(synced,"x0","mix",.6);setParameter(synced,"x0","syncMode",1);setParameter(synced,"x0","syncDivision",4);
  auto free250=tailPatch({"delay"});setParameter(free250,"x0","mix",.6);setParameter(free250,"x0","timeMs",250);
  auto free500=tailPatch({"delay"});setParameter(free500,"x0","mix",.6);setParameter(free500,"x0","timeMs",500);
  const auto syncedCompiled=engine::compilePatch(synced).patch;
  // One second, so a 250 ms and a 500 ms repeat are both inside the window.
  const auto second=[&](const engine::CompiledPatch&c,double tempo){return render(c,128,{},tempo,100,48000);};
  ok&=expect(distance(second(syncedCompiled,engine::fallbackTempoBpm),second(engine::compilePatch(free250).patch,engine::fallbackTempoBpm))==0.f,"1/8 at the 120 BPM fallback is the 250 ms free delay exactly");
  ok&=expect(distance(second(syncedCompiled,60.0),second(engine::compilePatch(free500).patch,engine::fallbackTempoBpm))==0.f,"1/8 at 60 BPM is the 500 ms free delay exactly");
  ok&=expect(distance(second(syncedCompiled,engine::fallbackTempoBpm),second(syncedCompiled,60.0))>.1f,"the host tempo changes what a synced delay renders");
  ok&=expect(distance(second(syncedCompiled,engine::fallbackTempoBpm),second(syncedCompiled,0.0))==0.f,"an absent or out-of-range tempo falls back to 120 BPM");
  // A macro is the one modulation source a stage that runs once for the whole mix can read.
  auto macroTail=tailPatch({"delay"});setParameter(macroTail,"x0","mix",.6);setParameter(macroTail,"x0","timeMs",5);macroTail.matrix={{"t1",true,domain::ModulationSource::macro1,"x0","mix",-.6}};
  const auto macroCompiled=engine::compilePatch(macroTail).patch;domain::HostControls macroUp;macroUp.macros[0]=1;
  ok&=expect(distance(render(macroCompiled,128),render(macroCompiled,128,macroUp))>.1f,"a macro row reaches an effects parameter in the global tail");
 }
 return ok;}
