#include "iupac/engine/Engine.hpp"

#include <algorithm>
#include <cmath>
#include <map>
#include <set>
#include <string_view>
#include <vector>

namespace iupac::engine {
namespace {
constexpr float safetyPeak=.891251f;
std::uint32_t hashId(std::string_view s) noexcept {std::uint32_t h=2166136261u;for(auto c:s){h^=static_cast<std::uint8_t>(c);h*=16777619u;}return h;}
const domain::ParameterValue* valueOf(const domain::Node& n,std::string_view id){auto i=std::ranges::find(n.parameters,id,&domain::ParameterValue::id);return i==n.parameters.end()?nullptr:&*i;}
float scalar(const domain::Node& n,std::string_view id,float fallback){auto* v=valueOf(n,id);return v&&!v->values.empty()?static_cast<float>(v->values[0]):fallback;}
ModuleValues moduleValues(const domain::Node& n){ModuleValues v;auto copy=[&](std::string_view id,auto& d){if(auto* s=valueOf(n,id))for(std::size_t i=0;i<std::min(d.size(),s->values.size());++i)d[i]=static_cast<float>(s->values[i]);};copy("partialAmplitudes",v.amplitudes);copy("partialRatios",v.ratios);copy("partialPans",v.pans);copy("modeRatios",v.modeRatios);copy("modeLevels",v.modeLevels);v.carrierRatio=scalar(n,"carrierRatio",1);v.modulatorRatio=scalar(n,"modulatorRatio",1);v.index=scalar(n,"index",0);v.burstMilliseconds=scalar(n,"burstMs",80);v.tuneRatio=scalar(n,"tuneRatio",1);v.combFeedback=scalar(n,"combFeedback",.4f);v.modalQ=scalar(n,"modalQ",3);v.cutoff=scalar(n,"cutoff",1000);v.q=scalar(n,"q",.707f);v.drive=scalar(n,"drive",1);v.wet=scalar(n,"wet",1);v.level=scalar(n,"level",1);v.pan=scalar(n,"pan",0);v.outputLevel=scalar(n,"outputLevel",1);v.mode=static_cast<int>(scalar(n,"mode",0));v.color=static_cast<int>(scalar(n,"color",0));v.detuneCents=scalar(n,"detuneCents",12);v.unisonSpread=scalar(n,"unisonSpread",.5f);v.phaseRandom=scalar(n,"phaseRandom",0);v.drift=scalar(n,"drift",0);v.harmonicityMorph=scalar(n,"harmonicityMorph",0);v.oddEvenBalance=scalar(n,"oddEvenBalance",0);v.symmetry=scalar(n,"symmetry",.5f);v.fine=scalar(n,"fine",0);v.keytrack=scalar(n,"keytrack",1);v.modInDepth=scalar(n,"modInDepth",0);v.exciteDepth=scalar(n,"exciteDepth",0);v.envAmount=scalar(n,"envAmount",0);v.rate=scalar(n,"rate",.5f);v.depth=scalar(n,"depth",.3f);v.feedback=scalar(n,"feedback",0);v.mix=scalar(n,"mix",.3f);v.timeMs=scalar(n,"timeMs",375);v.spread=scalar(n,"spread",0);v.damping=scalar(n,"damping",.4f);v.size=scalar(n,"size",.5f);v.decaySeconds=scalar(n,"decaySeconds",2);v.preDelayMs=scalar(n,"preDelayMs",20);v.width=scalar(n,"width",1);v.bassMonoHz=scalar(n,"bassMonoHz",120);v.unisonVoices=static_cast<int>(scalar(n,"unisonVoices",1));v.octave=static_cast<int>(scalar(n,"octave",0));v.coarse=static_cast<int>(scalar(n,"coarse",0));v.waveform=static_cast<int>(scalar(n,"waveform",0));v.curve=static_cast<int>(scalar(n,"curve",0));v.voices=static_cast<int>(scalar(n,"voices",2));v.syncMode=static_cast<int>(scalar(n,"syncMode",0));v.syncDivision=static_cast<int>(scalar(n,"syncDivision",4));return v;}
std::optional<ParameterTarget> targetFor(std::string_view id){static constexpr std::array<std::pair<std::string_view,ParameterTarget>,37> p{{{"carrierRatio",ParameterTarget::carrierRatio},{"modulatorRatio",ParameterTarget::modulatorRatio},{"index",ParameterTarget::index},{"burstMs",ParameterTarget::burstMilliseconds},{"tuneRatio",ParameterTarget::tuneRatio},{"combFeedback",ParameterTarget::combFeedback},{"modalQ",ParameterTarget::modalQ},{"cutoff",ParameterTarget::cutoff},{"q",ParameterTarget::q},{"drive",ParameterTarget::drive},{"wet",ParameterTarget::wet},{"level",ParameterTarget::level},{"pan",ParameterTarget::pan},{"outputLevel",ParameterTarget::outputLevel},{"detuneCents",ParameterTarget::detuneCents},{"unisonSpread",ParameterTarget::unisonSpread},{"drift",ParameterTarget::drift},{"harmonicityMorph",ParameterTarget::harmonicityMorph},{"oddEvenBalance",ParameterTarget::oddEvenBalance},{"symmetry",ParameterTarget::symmetry},{"fine",ParameterTarget::fine},{"keytrack",ParameterTarget::keytrack},{"modInDepth",ParameterTarget::modInDepth},{"exciteDepth",ParameterTarget::exciteDepth},{"envAmount",ParameterTarget::envAmount},{"rate",ParameterTarget::rate},{"depth",ParameterTarget::depth},{"feedback",ParameterTarget::feedback},{"mix",ParameterTarget::mix},{"timeMs",ParameterTarget::timeMs},{"spread",ParameterTarget::spread},{"damping",ParameterTarget::damping},{"size",ParameterTarget::size},{"decaySeconds",ParameterTarget::decaySeconds},{"preDelayMs",ParameterTarget::preDelayMs},{"width",ParameterTarget::width},{"bassMonoHz",ParameterTarget::bassMonoHz}}};for(auto [name,target]:p)if(id==name)return target;return{};}
float& targetValue(ModuleValues& v,ParameterTarget t) noexcept {switch(t){case ParameterTarget::carrierRatio:return v.carrierRatio;case ParameterTarget::modulatorRatio:return v.modulatorRatio;case ParameterTarget::index:return v.index;case ParameterTarget::burstMilliseconds:return v.burstMilliseconds;case ParameterTarget::tuneRatio:return v.tuneRatio;case ParameterTarget::combFeedback:return v.combFeedback;case ParameterTarget::modalQ:return v.modalQ;case ParameterTarget::cutoff:return v.cutoff;case ParameterTarget::q:return v.q;case ParameterTarget::drive:return v.drive;case ParameterTarget::wet:return v.wet;case ParameterTarget::level:return v.level;case ParameterTarget::pan:return v.pan;case ParameterTarget::outputLevel:return v.outputLevel;case ParameterTarget::detuneCents:return v.detuneCents;case ParameterTarget::unisonSpread:return v.unisonSpread;case ParameterTarget::drift:return v.drift;case ParameterTarget::harmonicityMorph:return v.harmonicityMorph;case ParameterTarget::oddEvenBalance:return v.oddEvenBalance;case ParameterTarget::symmetry:return v.symmetry;case ParameterTarget::fine:return v.fine;case ParameterTarget::keytrack:return v.keytrack;case ParameterTarget::modInDepth:return v.modInDepth;case ParameterTarget::exciteDepth:return v.exciteDepth;case ParameterTarget::envAmount:return v.envAmount;case ParameterTarget::rate:return v.rate;case ParameterTarget::depth:return v.depth;case ParameterTarget::feedback:return v.feedback;case ParameterTarget::mix:return v.mix;case ParameterTarget::timeMs:return v.timeMs;case ParameterTarget::spread:return v.spread;case ParameterTarget::damping:return v.damping;case ParameterTarget::size:return v.size;case ParameterTarget::decaySeconds:return v.decaySeconds;case ParameterTarget::preDelayMs:return v.preDelayMs;case ParameterTarget::width:return v.width;case ParameterTarget::bassMonoHz:return v.bassMonoHz;}return v.outputLevel;}
float targetValue(const ModuleValues&v,ParameterTarget t)noexcept{return targetValue(const_cast<ModuleValues&>(v),t);}
float normalize(float v,const CompiledRow&r)noexcept{v=std::clamp(v,r.minimum,r.maximum);return r.scale==domain::ParameterScale::logarithmic?std::log(v/r.minimum)/std::log(r.maximum/r.minimum):(v-r.minimum)/(r.maximum-r.minimum);}
float normalize(float v,const CompiledRange&r)noexcept{v=std::clamp(v,r.minimum,r.maximum);return r.scale==domain::ParameterScale::logarithmic?std::log(v/r.minimum)/std::log(r.maximum/r.minimum):(v-r.minimum)/(r.maximum-r.minimum);}
float denormalize(float v,const CompiledRow&r)noexcept{v=std::clamp(v,0.f,1.f);return r.scale==domain::ParameterScale::logarithmic?r.minimum*std::pow(r.maximum/r.minimum,v):r.minimum+v*(r.maximum-r.minimum);}
float lerpValue(float a,float b,float x)noexcept{return std::lerp(a,b,x);}
ModuleValues interpolate(const ModuleValues&a,const ModuleValues&b,float x)noexcept{ModuleValues r=b;for(std::size_t i=0;i<r.amplitudes.size();++i){r.amplitudes[i]=lerpValue(a.amplitudes[i],b.amplitudes[i],x);r.ratios[i]=lerpValue(a.ratios[i],b.ratios[i],x);r.pans[i]=lerpValue(a.pans[i],b.pans[i],x);}for(std::size_t i=0;i<r.modeRatios.size();++i){r.modeRatios[i]=lerpValue(a.modeRatios[i],b.modeRatios[i],x);r.modeLevels[i]=lerpValue(a.modeLevels[i],b.modeLevels[i],x);}// Every continuous scalar is a ParameterTarget, so the crossfade covers the whole catalog without a second list.
 for(std::size_t i=0;i<parameterTargetCount;++i){const auto target=static_cast<ParameterTarget>(i);targetValue(r,target)=lerpValue(targetValue(a,target),targetValue(b,target),x);}return r;}
domain::HostControls interpolate(const domain::HostControls&a,const domain::HostControls&b,float x)noexcept{domain::HostControls r=b;for(std::size_t i=0;i<r.macros.size();++i)r.macros[i]=std::lerp(a.macros[i],b.macros[i],static_cast<double>(x));r.outputGain=std::lerp(a.outputGain,b.outputGain,static_cast<double>(x));r.width=std::lerp(a.width,b.width,static_cast<double>(x));r.masterTune=std::lerp(a.masterTune,b.masterTune,static_cast<double>(x));return r;}
}

std::uint32_t hashNodeId(std::string_view id) noexcept {return hashId(id);}
std::optional<ParameterTarget> parameterTarget(std::string_view id) noexcept {return targetFor(id);}

ModuleValues applyModulation(const CompiledPatch& patch,std::size_t node,const ModuleValues& base,const ModulationInputs& inputs)noexcept
{
 ModuleValues values=base;
 if(patch.targetCount==0){for(std::size_t targetIndex=0;targetIndex<=static_cast<std::size_t>(ParameterTarget::outputLevel);++targetIndex){auto target=static_cast<ParameterTarget>(targetIndex);const CompiledRow*definition=nullptr;float contribution=0;for(std::size_t rowIndex=0;rowIndex<patch.rowCount;++rowIndex){const auto&row=patch.rows[rowIndex];if(row.node==node&&row.target==target){definition=&row;contribution+=row.depth*inputs[static_cast<std::size_t>(row.source)];}}if(definition){auto&value=targetValue(values,target);value=denormalize(normalize(value,*definition)+contribution,*definition);}}return values;}
 for(std::size_t targetIndex=0;targetIndex<patch.targetCount;++targetIndex){const auto&target=patch.targets[targetIndex];if(target.node!=node)continue;float contribution=0;for(std::size_t i=0;i<target.rowCount;++i){const auto&row=patch.rows[target.rows[i]];contribution+=row.depth*inputs[static_cast<std::size_t>(row.source)];}CompiledRow definition{};definition.minimum=target.minimum;definition.maximum=target.maximum;definition.scale=target.scale;auto&value=targetValue(values,target.target);value=denormalize(normalize(value,definition)+contribution,definition);}
 return values;
}

namespace {
using VoiceValues = std::array<ModuleValues, domain::maximumNodes>;

VoiceValues applyAllModulation(const CompiledPatch& patch, const ModulationInputs& inputs) noexcept
{
 VoiceValues values{};
 for(std::size_t node=0;node<patch.nodeCount;++node)values[node]=patch.nodes[node].values;
 for(std::size_t targetIndex=0;targetIndex<patch.targetCount;++targetIndex){const auto&target=patch.targets[targetIndex];float contribution=0;for(std::size_t i=0;i<target.rowCount;++i){const auto&row=patch.rows[target.rows[i]];contribution+=row.depth*inputs[static_cast<std::size_t>(row.source)];}CompiledRow definition{};definition.minimum=target.minimum;definition.maximum=target.maximum;definition.scale=target.scale;targetValue(values[target.node],target.target)=denormalize(target.normalizedBase+contribution,definition);}
 return values;
}

void prepareTargets(CompiledPatch& patch) noexcept
{
 patch.targetCount=0;
 patch.outputEdges={};patch.tailOutputEdges={};for(auto&list:patch.incomingEdges)list={};for(std::size_t edgeIndex=0;edgeIndex<patch.edgeCount;++edgeIndex){const auto&edge=patch.edges[edgeIndex];auto&list=edge.toOutput?(edge.source>=patch.tailStart?patch.tailOutputEdges:patch.outputEdges):patch.incomingEdges[edge.destination];list.edges[list.count++]=static_cast<std::uint8_t>(edgeIndex);}
 for(std::size_t rowIndex=0;rowIndex<patch.rowCount;++rowIndex){const auto&row=patch.rows[rowIndex];CompiledTarget*group=nullptr;for(std::size_t i=0;i<patch.targetCount;++i)if(patch.targets[i].node==row.node&&patch.targets[i].target==row.target){group=&patch.targets[i];break;}if(!group){group=&patch.targets[patch.targetCount++];*group={};group->node=row.node;group->target=row.target;group->minimum=row.minimum;group->maximum=row.maximum;group->scale=row.scale;}group->rows[group->rowCount++]=static_cast<std::uint8_t>(rowIndex);}
 // (#144) Resolve each group's normalized base once. It is exactly the expression the per-sample
 // pass used to run — the group's unmodulated node value, clamped to the group's range and
 // normalized on the group's scale — so the sum it feeds is unchanged; only the repetition goes.
 for(std::size_t i=0;i<patch.targetCount;++i){auto&target=patch.targets[i];CompiledRow definition{};definition.minimum=target.minimum;definition.maximum=target.maximum;definition.scale=target.scale;target.normalizedBase=normalize(targetValue(patch.nodes[target.node].values,target.target),definition);}
 const auto voiceTargets=std::stable_partition(patch.targets.begin(),patch.targets.begin()+patch.targetCount,[&](const CompiledTarget&t){return t.node<patch.tailStart;});
 patch.voiceTargetCount=static_cast<std::uint8_t>(voiceTargets-patch.targets.begin());
}

// `begin`/`end` select one half of the target partition: voices run [0, voiceTargetCount) and the
// global tail runs the rest, each with its own value array and input cache.
void updateModulation(const CompiledPatch&patch,const ModulationInputs&inputs,VoiceValues&values,ModulationInputs&previous,bool&ready,std::size_t begin,std::size_t end)noexcept
{
 if(!ready){for(std::size_t node=0;node<patch.nodeCount;++node)values[node]=patch.nodes[node].values;previous.fill(std::numeric_limits<float>::quiet_NaN());ready=true;}
 for(std::size_t targetIndex=begin;targetIndex<end;++targetIndex){const auto&target=patch.targets[targetIndex];bool changed=false;float contribution=0;for(std::size_t i=0;i<target.rowCount;++i){const auto&row=patch.rows[target.rows[i]];const auto sourceIndex=static_cast<std::size_t>(row.source);changed|=inputs[sourceIndex]!=previous[sourceIndex];contribution+=row.depth*inputs[sourceIndex];}if(changed){CompiledRow definition{};definition.minimum=target.minimum;definition.maximum=target.maximum;definition.scale=target.scale;targetValue(values[target.node],target.target)=denormalize(target.normalizedBase+contribution,definition);}}
 previous=inputs;
}
}

CompileResult compilePatch(const domain::Patch& source){CompileResult result;if(auto e=domain::validate(source);!e.empty()){result.error=e;return result;}std::map<std::string,std::size_t,std::less<>> original;for(std::size_t i=0;i<source.nodes.size();++i)original.emplace(source.nodes[i].id,i);std::set<std::string,std::less<>> live;std::vector<std::string> frontier;for(auto&e:source.edges)if(e.destination=="output"&&live.insert(e.source).second)frontier.push_back(e.source);while(!frontier.empty()){auto d=frontier.back();frontier.pop_back();for(auto&e:source.edges)if(e.destination==d&&live.insert(e.source).second)frontier.push_back(e.source);}std::map<std::string,int,std::less<>> indegree;for(auto&id:live)indegree[id]=0;for(auto&e:source.edges)if(e.destination!="output"&&live.contains(e.source)&&live.contains(e.destination))++indegree[e.destination];std::set<std::string,std::less<>> ready;for(auto&[id,n]:indegree)if(!n)ready.insert(id);std::vector<std::string> order;while(!ready.empty()){auto id=*ready.begin();ready.erase(ready.begin());order.push_back(id);for(auto&e:source.edges)if(e.source==id&&e.destination!="output"&&live.contains(e.destination)&&!--indegree[e.destination])ready.insert(e.destination);}if(order.size()!=live.size()){result.error="compiler found cycle";return result;}
 // Effects nodes are the global post-mixer tail, so they occupy the last slots. No per-voice node can
 // depend on one (the validator rejects a tail edge into a per-voice node), so a stable partition of a
 // valid topological order is still a valid topological order.
 std::stable_partition(order.begin(),order.end(),[&](const std::string& id){return !domain::moduleCatalog()[static_cast<std::size_t>(source.nodes[original.at(id)].type)].effects;});
 result.patch.tailStart=static_cast<std::uint8_t>(std::ranges::count_if(order,[&](const std::string& id){return !domain::moduleCatalog()[static_cast<std::size_t>(source.nodes[original.at(id)].type)].effects;}));std::map<std::string,std::uint8_t,std::less<>> slots;for(std::size_t i=0;i<order.size();++i){slots.emplace(order[i],static_cast<std::uint8_t>(i));auto&n=source.nodes[original.at(order[i])];result.patch.nodes[i]={n.type,moduleValues(n),hashId(n.id)};auto&md=domain::moduleCatalog()[static_cast<std::size_t>(n.type)];for(auto&pd:md.parameters)if(pd.modulatable)if(auto target=targetFor(pd.id))result.patch.nodes[i].ranges[static_cast<std::size_t>(*target)]={static_cast<float>(pd.minimum),static_cast<float>(pd.maximum),pd.scale,true};}result.patch.nodeCount=static_cast<std::uint8_t>(order.size());for(auto&e:source.edges)if(live.contains(e.source)&&(e.destination=="output"||live.contains(e.destination))){auto&o=result.patch.edges[result.patch.edgeCount++];o.source=slots.at(e.source);o.gain=static_cast<float>(e.gain);o.toOutput=e.destination=="output";o.destination=o.toOutput?0:slots.at(e.destination);o.port=e.port;}for(auto&r:source.matrix)if(r.enabled&&live.contains(r.destinationNode)){auto slot=slots.at(r.destinationNode);auto&n=source.nodes[original.at(r.destinationNode)];auto&md=domain::moduleCatalog()[static_cast<std::size_t>(n.type)];auto*pd=domain::findParameter(md,r.destinationParameter);auto target=targetFor(r.destinationParameter);if(!pd||!target){result.error="unsupported matrix destination";return result;}result.patch.rows[result.patch.rowCount++]={r.source,slot,*target,static_cast<float>(r.depth),static_cast<float>(pd->minimum),static_cast<float>(pd->maximum),pd->scale};}
 // D8 filter panel shortcuts (#126). `keytrack` and `envAmount` are not a second modulation path:
 // they are compiled here into the same row array the explicit matrix fills, as keyTracking->cutoff
 // and E2->cutoff at their declared depth. buildTargets() then groups every row aimed at that
 // node's cutoff into one CompiledTarget, so an explicit cutoff row and a shortcut are summed and
 // passed through a single normalize/denormalize clamp rather than clamped twice. Both are 0 by
 // default, and a zero-depth row would be a no-op contribution anyway, so a patch that does not use
 // them compiles exactly the rows it did before.
 {
  const auto&filterDescriptor=domain::moduleCatalog()[static_cast<std::size_t>(domain::ModuleType::filter)];
  const auto* cutoffDescriptor=domain::findParameter(filterDescriptor,"cutoff");
  for(std::size_t i=0;i<order.size()&&cutoffDescriptor;++i)
  {
   const auto&n=source.nodes[original.at(order[i])];
   if(n.type!=domain::ModuleType::filter)continue;
   const std::array<std::pair<domain::ModulationSource,float>,2> shortcuts{{
    {domain::ModulationSource::keyTracking,scalar(n,"keytrack",0)},{domain::ModulationSource::e2,scalar(n,"envAmount",0)}}};
   for(auto [modulationSource,depth]:shortcuts)
    if(depth!=0.0f&&result.patch.rowCount<compiledRowCapacity)
     result.patch.rows[result.patch.rowCount++]={modulationSource,static_cast<std::uint8_t>(i),ParameterTarget::cutoff,depth,
                                                 static_cast<float>(cutoffDescriptor->minimum),static_cast<float>(cutoffDescriptor->maximum),cutoffDescriptor->scale};
  }
 }
 result.patch.envelopes=source.envelopes;result.patch.lfos=source.lfos;result.patch.noiseSeed=source.noiseSeed;return result;}

class Engine::Impl {public:
 struct Voice{std::array<ModuleProcessor,domain::maximumNodes> modules;std::array<std::unique_ptr<ModuleProcessor::CombDelay>,2> combs;ModulatorBank modulators;VoiceValues modulatedValues{},transitionValues{};ModulationInputs previousInputs{};std::array<float,domain::maximumNodes> left{},right{};int note{},channel{1},cachedNote{-1};float velocity{},lastL{},lastR{},tailL{},tailR{},level{},cachedTune{std::numeric_limits<float>::quiet_NaN()},cachedHz{440};std::uint32_t fade{};std::uint64_t age{};bool held{},sustained{},active{},forcedStop{},modulationReady{},usingTransition{};};
 // The global effects tail: one set of processors and buses for the whole bank, never per voice.
 std::array<ModuleProcessor,domain::maximumNodes> tailModules;
 std::array<float,domain::maximumNodes> tailOutL{},tailOutR{},tailBusL{},tailBusR{};
 // The chorus's and the delay's prepared lines. The fixed slot set holds exactly one of each type,
 // so two lines cover any patch; both are allocated in prepare() and merely pointed at when a patch
 // is published, which is what keeps setPatch() allocation-free on the audio thread.
 std::unique_ptr<ModuleProcessor::CombDelay> tailChorusLine,tailDelayLine;
 // The reverb's prepared network (#124). One of it, for the same reason: the fixed slot set holds
 // exactly one reverb, and C4 state that multiplied by voice count would not fit the 128 MiB bound.
 std::unique_ptr<ReverbNetwork> tailReverb;
 // Tail modulation. A global stage has no voice, so the only modulation sources with a single
 // well-defined value here are the four macros; the rest read zero. This is the same cached pass
 // the voices run, restricted to [tailStart, nodeCount).
 VoiceValues tailValues{};ModulationInputs tailPreviousInputs{};bool tailModulationReady{};
 double tempo{fallbackTempoBpm};
 std::array<Voice,maximumVoices> voices;std::array<float,16>bend{},cc1{};std::array<bool,16>sustain{};CompiledPatch patch{},previousPatch{};domain::HostControls controls{},previousControls{};std::uint64_t age{},guardHits{},midiOverflow{},smoothSample{},smoothLength{1};std::unique_ptr<juce::dsp::Oversampling<float>> oversampling;juce::dsp::Limiter<float> limiter;juce::AudioBuffer<float> output;double outputRate{48000};std::size_t maxBlock{};float dcXL{},dcYL{},dcXR{},dcYR{};
 void prepare(double rate,std::size_t block){outputRate=rate;maxBlock=std::max<std::size_t>(1,block);smoothLength=static_cast<std::uint64_t>(std::max(1.0,internalSampleRate(rate)*.020));output.setSize(2,static_cast<int>(maxBlock),false,false,true);oversampling=std::make_unique<juce::dsp::Oversampling<float>>(2,1,juce::dsp::Oversampling<float>::filterHalfBandPolyphaseIIR,true,true);oversampling->initProcessing(maxBlock);limiter.prepare({rate,static_cast<juce::uint32>(maxBlock),2});limiter.setThreshold(-1.f);limiter.setRelease(20.f);juce::dsp::ProcessSpec spec{internalSampleRate(rate),static_cast<juce::uint32>(maxBlock*2),2};for(auto&v:voices){v.modulators.prepare(internalSampleRate(rate));for(auto&c:v.combs){c=std::make_unique<ModuleProcessor::CombDelay>(110000);c->prepare(spec);}for(auto&m:v.modules)m.prepare(internalSampleRate(rate),maxBlock*2);}tailChorusLine=std::make_unique<ModuleProcessor::CombDelay>(static_cast<int>(maximumChorusDelaySeconds*internalSampleRate(rate))+4);tailChorusLine->prepare(spec);
  tailDelayLine=std::make_unique<ModuleProcessor::CombDelay>(static_cast<int>(maximumDelaySeconds*internalSampleRate(rate))+4);tailDelayLine->prepare(spec);
  tailReverb=std::make_unique<ReverbNetwork>();tailReverb->prepare(spec);
  for(auto&m:tailModules){m.prepare(internalSampleRate(rate),maxBlock*2);m.setTempo(tempo);}
  // prepare() replaces the tail's lines and network, so re-bind the processors' pointers to the new
  // ones before anything can render: a prepare() between two setPatch() calls must not leave a live
  // effects node pointing at the storage this call just freed.
  configureTail();reset();}
 void reset()noexcept{bend.fill(0);cc1.fill(0);sustain.fill(false);age=guardHits=midiOverflow=0;dcXL=dcYL=dcXR=dcYR=0;if(oversampling)oversampling->reset();limiter.reset();
  // The tail owns delay lines and reverb state, so a prepare or a structural bank switch clears it.
  if(tailChorusLine)tailChorusLine->reset();if(tailDelayLine)tailDelayLine->reset();if(tailReverb)tailReverb->reset();for(auto&m:tailModules)m.reset();tailModulationReady=false;tailOutL.fill(0);tailOutR.fill(0);tailBusL.fill(0);tailBusR.fill(0);for(auto&v:voices){v.active=v.held=v.sustained=v.forcedStop=v.modulationReady=v.usingTransition=false;v.cachedTune=std::numeric_limits<float>::quiet_NaN();v.fade=0;v.lastL=v.lastR=v.tailL=v.tailR=v.level=0;v.modulators.reset();for(auto&m:v.modules)m.reset();}}
 // Tail types come from the compiled patch, not from a voice; setType clears the effect's state.
 void configureTail()noexcept{for(std::size_t i=0;i<domain::maximumNodes;++i){const auto type=i>=patch.tailStart&&i<patch.nodeCount?patch.nodes[i].type:domain::ModuleType::mixer;
  // The pointer is handed in before setType, because setType resets the processor and the reset
  // clears the line it is about to own.
  tailModules[i].setEffectDelay(type==domain::ModuleType::chorus?tailChorusLine.get():type==domain::ModuleType::delay?tailDelayLine.get():nullptr);tailModules[i].setReverbNetwork(type==domain::ModuleType::reverb?tailReverb.get():nullptr);tailModules[i].setType(type);tailModules[i].setTempo(tempo);}
  tailModulationReady=false;tailOutL.fill(0);tailOutR.fill(0);tailBusL.fill(0);tailBusR.fill(0);}
 void configure(Voice&v)noexcept{v.modulators.setTempo(tempo);v.modulators.configure(patch.envelopes,patch.lfos,patch.noiseSeed);std::size_t comb=0;for(std::size_t i=0;i<patch.nodeCount;++i){v.modules[i].setCombDelay(patch.nodes[i].type==domain::ModuleType::resonator?v.combs[comb++].get():nullptr);v.modules[i].setType(patch.nodes[i].type);}}
 void noteOn(int ch,int note,float velocity){Voice*pick=nullptr;for(auto&v:voices)if(!v.active){pick=&v;break;}if(!pick)for(auto&v:voices)if(!v.held&&(!pick||v.level<pick->level||(v.level==pick->level&&v.age<pick->age)))pick=&v;if(!pick)pick=&*std::ranges::min_element(voices,{},&Voice::age);if(pick->active){pick->tailL=pick->lastL;pick->tailR=pick->lastR;pick->fade=static_cast<std::uint32_t>(std::max(1.,internalSampleRate(outputRate)*.005));}else{pick->tailL=pick->tailR=0;pick->fade=0;}for(auto&m:pick->modules)m.reset();pick->modulators.setTempo(tempo);pick->modulators.configure(patch.envelopes,patch.lfos,patch.noiseSeed);pick->modulators.reset();pick->note=note;pick->channel=ch;pick->velocity=velocity;pick->level=0;pick->age=++age;pick->active=pick->held=true;pick->sustained=pick->forcedStop=false;pick->modulators.noteOn();for(std::size_t i=0;i<patch.nodeCount;++i)pick->modules[i].noteOn(note,ch,patch.noiseSeed,patch.nodes[i].idHash);}
 void noteOff(int ch,int note)noexcept{Voice*old=nullptr;for(auto&v:voices)if(v.active&&v.held&&v.channel==ch&&v.note==note&&(!old||v.age<old->age))old=&v;if(!old)return;old->held=false;if(sustain[ch-1])old->sustained=true;else old->modulators.noteOff();}
 void allNotesOff(int ch,bool immediate)noexcept{for(auto&v:voices)if(v.active&&(!ch||v.channel==ch)){v.held=v.sustained=false;v.modulators.noteOff();if(immediate){v.forcedStop=true;v.tailL=v.lastL;v.tailR=v.lastR;v.fade=static_cast<std::uint32_t>(std::max(1.,internalSampleRate(outputRate)*.005));}}}
 void event(const MidiEvent&e){if(e.channel<1||e.channel>16||e.data1>127||e.data2>127||e.bend>16383)return;auto ch=static_cast<int>(e.channel);if(e.type==MidiEventType::noteOn){if(!e.data2)noteOff(ch,e.data1);else noteOn(ch,e.data1,e.data2/127.f);}else if(e.type==MidiEventType::noteOff)noteOff(ch,e.data1);else if(e.type==MidiEventType::pitchBend)bend[ch-1]=std::clamp((static_cast<int>(e.bend)-8192)/8192.f,-1.f,1.f);else if(e.type==MidiEventType::controlChange&&e.data1==1)cc1[ch-1]=e.data2/127.f;else if(e.type==MidiEventType::controlChange&&e.data1==64){bool down=e.data2>=64;if(sustain[ch-1]&&!down)for(auto&v:voices)if(v.active&&v.channel==ch&&v.sustained){v.sustained=false;v.modulators.noteOff();}sustain[ch-1]=down;}else if(e.type==MidiEventType::controlChange&&e.data1==120)allNotesOff(ch,true);else if(e.type==MidiEventType::controlChange&&e.data1==123)allNotesOff(ch,false);}
 float source(domain::ModulationSource s,const Voice&v,const std::array<float,6>&m)const noexcept{auto i=static_cast<std::size_t>(s);if(i<5)return m[i];switch(s){case domain::ModulationSource::e4:return m[5];case domain::ModulationSource::velocity:return v.velocity;case domain::ModulationSource::keyTracking:return std::clamp((v.note-60)/36.f,-1.f,1.f);case domain::ModulationSource::pitchBend:return bend[v.channel-1];case domain::ModulationSource::cc1:return cc1[v.channel-1];case domain::ModulationSource::macro1:case domain::ModulationSource::macro2:case domain::ModulationSource::macro3:case domain::ModulationSource::macro4:{const float x=smoothSample>=smoothLength?1.f:static_cast<float>(smoothSample)/static_cast<float>(smoothLength);const auto macro=i-static_cast<std::size_t>(domain::ModulationSource::macro1);return std::lerp(static_cast<float>(previousControls.macros[macro]),static_cast<float>(controls.macros[macro]),x);}default:return 0;}}
 void renderInternal(juce::dsp::AudioBlock<float>&b,std::size_t begin,std::size_t end)noexcept
 {
  auto*lout=b.getChannelPointer(0);auto*rout=b.getChannelPointer(1);
  for(std::size_t s=begin*2;s<end*2;++s){const float x=smoothSample>=smoothLength?1.f:static_cast<float>(smoothSample)/static_cast<float>(smoothLength);const auto blockControls=x>=1.f?controls:interpolate(previousControls,controls,x);float sumL=0,sumR=0;const bool hasTail=patch.tailStart<patch.nodeCount;if(hasTail)for(std::size_t n=patch.tailStart;n<patch.nodeCount;++n){tailBusL[n]=0;tailBusR[n]=0;}
   for(auto&v:voices)if(v.active){auto mods=v.modulators.next();ModulationInputs inputs{};for(std::size_t i=0;i<inputs.size();++i)inputs[i]=source(static_cast<domain::ModulationSource>(i),v,mods);const VoiceValues*values=&v.modulatedValues;v.usingTransition=x<1.f;if(x>=1.f)updateModulation(patch,inputs,v.modulatedValues,v.previousInputs,v.modulationReady,0,patch.voiceTargetCount);else{v.transitionValues=applyAllModulation(patch,inputs);const auto oldValues=applyAllModulation(previousPatch,inputs);for(std::size_t n=0;n<patch.nodeCount;++n)v.transitionValues[n]=interpolate(oldValues[n],v.transitionValues[n],x);values=&v.transitionValues;}const float tune=static_cast<float>(blockControls.masterTune)+2*bend[v.channel-1];if(tune!=v.cachedTune||v.note!=v.cachedNote){v.cachedTune=tune;v.cachedNote=v.note;v.cachedHz=440*std::pow(2.f,(v.note-69+tune)/12.f);}for(std::size_t n=0;n<patch.tailStart;++n){const auto&nodeValues=(*values)[n];float inL=0,inR=0,modInL=0,modInR=0;bool audioRateCabled=false;const auto&incoming=patch.incomingEdges[n];for(std::size_t i=0;i<incoming.count;++i){const auto e=incoming.edges[i];const auto&edge=patch.edges[e];const float edgeGain=x>=1.f?edge.gain:std::lerp(previousPatch.edges[e].gain,edge.gain,x);
    // D8 audio-rate modulation inputs (#127). The typed ports sum exactly like the ordinary one —
    // multi-connection, same gain knob, same transition lerp — into their own accumulator, which is
    // handed to the node as its `modIn`/`exciteIn` signal. Compiled order is topological, so the
    // driver has already rendered this sample. An uncabled port stays an empty span below.
    if(edge.port!=domain::AudioPort::in){audioRateCabled=true;modInL+=v.left[edge.source]*edgeGain;modInR+=v.right[edge.source]*edgeGain;continue;}
    inL+=v.left[edge.source]*edgeGain;inR+=v.right[edge.source]*edgeGain;}
   v.modules[n].process(nodeValues,v.cachedHz,{&inL,1},{&inR,1},{&v.left[n],1},{&v.right[n],1},audioRateCabled?std::span<const float>{&modInL,1}:std::span<const float>{},audioRateCabled?std::span<const float>{&modInR,1}:std::span<const float>{});}float l=0,r=0;for(std::size_t i=0;i<patch.outputEdges.count;++i){const auto e=patch.outputEdges.edges[i];const auto&edge=patch.edges[e];const float edgeGain=x>=1.f?edge.gain:std::lerp(previousPatch.edges[e].gain,edge.gain,x);l+=v.left[edge.source]*edgeGain;r+=v.right[edge.source]*edgeGain;}const float gate=mods[0]*v.velocity;l*=gate;r*=gate;float voiceScale=1.f;if(v.fade){const auto fadeTotal=static_cast<float>(std::max(1.,internalSampleRate(outputRate)*.005));const float f=std::min(1.f,v.fade/fadeTotal);if(v.forcedStop){l=v.tailL*f;r=v.tailR*f;voiceScale=0;}else{l=l*(1-f)+v.tailL*f;r=r*(1-f)+v.tailR*f;voiceScale=1-f;}--v.fade;}
    // Edges into the effects region carry this voice's contribution to the global tail, gated by E1,
    // velocity and the same steal fade as its direct output contribution (ARCHITECTURE "Effects region").
    if(hasTail){const float tailGate=gate*voiceScale;for(std::size_t n=patch.tailStart;n<patch.nodeCount;++n){const auto&incoming=patch.incomingEdges[n];float tl=0,tr=0;for(std::size_t i=0;i<incoming.count;++i){const auto e=incoming.edges[i];const auto&edge=patch.edges[e];if(edge.source>=patch.tailStart||edge.port!=domain::AudioPort::in)continue;const float edgeGain=x>=1.f?edge.gain:std::lerp(previousPatch.edges[e].gain,edge.gain,x);tl+=v.left[edge.source]*edgeGain;tr+=v.right[edge.source]*edgeGain;}tailBusL[n]+=tl*tailGate;tailBusR[n]+=tr*tailGate;}}
    v.lastL=l;v.lastR=r;v.level=.999f*v.level+.001f*std::max(std::abs(l),std::abs(r));sumL+=l;sumR+=r;if((v.forcedStop&&!v.fade)||(!v.modulators.finalEnvelopeActive()&&!v.held&&!v.sustained&&!v.fade)){v.active=false;v.forcedStop=false;for(auto&m:v.modules)m.reset();}}
   // The global post-mixer tail: prepared once, run once per sample on the summed voice output.
   if(hasTail){
    // The tail's modulation inputs. Envelopes, LFOs, velocity, key tracking, bend and CC1 are all
    // per-voice or per-channel and have no single value in a stage that runs once for the whole
    // mix, so they read zero here; the four macros are global by construction (ARCHITECTURE
    // "Controls and state"), so a macro row into an effects parameter is the one that moves. The
    // pass is the cached one, so a static macro costs a comparison per row.
    ModulationInputs tailInputs{};for(std::size_t m=0;m<blockControls.macros.size();++m)tailInputs[static_cast<std::size_t>(domain::ModulationSource::macro1)+m]=static_cast<float>(blockControls.macros[m]);
    updateModulation(patch,tailInputs,tailValues,tailPreviousInputs,tailModulationReady,patch.voiceTargetCount,patch.targetCount);
    for(std::size_t n=patch.tailStart;n<patch.nodeCount;++n){float inL=tailBusL[n],inR=tailBusR[n];const auto&incoming=patch.incomingEdges[n];for(std::size_t i=0;i<incoming.count;++i){const auto e=incoming.edges[i];const auto&edge=patch.edges[e];if(edge.source<patch.tailStart)continue;const float edgeGain=x>=1.f?edge.gain:std::lerp(previousPatch.edges[e].gain,edge.gain,x);inL+=tailOutL[edge.source]*edgeGain;inR+=tailOutR[edge.source]*edgeGain;}
    tailModules[n].process(tailValues[n],440.f,{&inL,1},{&inR,1},{&tailOutL[n],1},{&tailOutR[n],1});}
    for(std::size_t i=0;i<patch.tailOutputEdges.count;++i){const auto e=patch.tailOutputEdges.edges[i];const auto&edge=patch.edges[e];const float edgeGain=x>=1.f?edge.gain:std::lerp(previousPatch.edges[e].gain,edge.gain,x);sumL+=tailOutL[edge.source]*edgeGain;sumR+=tailOutR[edge.source]*edgeGain;}}
   float mid=(sumL+sumR)*.5f,side=(sumL-sumR)*static_cast<float>(blockControls.width);sumL=mid+side;sumR=mid-side;float gain=std::pow(10.f,static_cast<float>(blockControls.outputGain)/20.f);sumL*=gain;sumR*=gain;float dl=sumL-dcXL+.995f*dcYL,dr=sumR-dcXR+.995f*dcYR;dcXL=sumL;dcYL=dl;dcXR=sumR;dcYR=dr;auto safe=[this](float v){if(!std::isfinite(v)){++guardHits;return 0.f;}if(std::abs(v)>safetyPeak){++guardHits;v=std::clamp(v,-safetyPeak,safetyPeak);}return v;};lout[s]=blockControls.bypass?0:safe(dl);rout[s]=blockControls.bypass?0:safe(dr);if(smoothSample<smoothLength)++smoothSample;}
 }
};
Engine::Engine():impl_(std::make_unique<Impl>()){}Engine::~Engine()=default;Engine::Engine(Engine&&)noexcept=default;Engine&Engine::operator=(Engine&&)noexcept=default;
void Engine::prepare(double r,std::size_t b)noexcept{sampleRate_=std::max(1.,r);maximumBlockSize_=std::max<std::size_t>(1,b);impl_->prepare(sampleRate_,maximumBlockSize_);}void Engine::reset()noexcept{impl_->reset();}void Engine::setPatch(const CompiledPatch&p){impl_->patch=impl_->previousPatch=p;prepareTargets(impl_->patch);prepareTargets(impl_->previousPatch);impl_->smoothSample=impl_->smoothLength;for(auto&v:impl_->voices)impl_->configure(v);impl_->configureTail();impl_->reset();}void Engine::setTempo(double bpm)noexcept{impl_->tempo=bpm;for(auto&m:impl_->tailModules)m.setTempo(bpm);for(auto&v:impl_->voices)v.modulators.setTempo(bpm);}
void Engine::setControls(const domain::HostControls&c)noexcept{impl_->previousControls=impl_->controls;impl_->controls=c;impl_->smoothSample=0;}
void Engine::updatePatchPreservingVoices(const CompiledPatch&p)noexcept{impl_->previousPatch=impl_->patch;impl_->patch=p;prepareTargets(impl_->patch);impl_->smoothSample=0;impl_->tailModulationReady=false;for(auto&v:impl_->voices){v.modulationReady=false;v.modulators.configure(p.envelopes,p.lfos,p.noiseSeed);}}
void Engine::render(std::span<float>left,std::span<float>right,std::span<const MidiEvent>events)noexcept{auto total=std::min(left.size(),right.size());if(!total)return;std::size_t offset=0,eventIndex=0,processed=0;while(offset<total){auto count=std::min(maximumBlockSize_,total-offset);impl_->output.clear();juce::dsp::AudioBlock<float>base(impl_->output);auto slice=base.getSubBlock(0,count);auto up=impl_->oversampling->processSamplesUp(slice);up.clear();std::size_t cursor=0;while(eventIndex<events.size()&&events[eventIndex].sampleOffset<offset+count&&processed<maximumMidiEventsPerBlock){auto eo=std::max<std::size_t>(cursor,events[eventIndex].sampleOffset>offset?events[eventIndex].sampleOffset-offset:0);impl_->renderInternal(up,cursor,eo);impl_->event(events[eventIndex]);cursor=eo;++eventIndex;++processed;}impl_->renderInternal(up,cursor,count);impl_->oversampling->processSamplesDown(slice);juce::dsp::ProcessContextReplacing<float>context(slice);impl_->limiter.process(context);for(std::size_t i=0;i<count;++i){auto guard=[this](float x){if(!std::isfinite(x)){++impl_->guardHits;return 0.f;}if(std::abs(x)>safetyPeak){++impl_->guardHits;return std::clamp(x,-safetyPeak,safetyPeak);}return x;};left[offset+i]=guard(impl_->output.getSample(0,static_cast<int>(i)));right[offset+i]=guard(impl_->output.getSample(1,static_cast<int>(i)));}offset+=count;}if(eventIndex<events.size()){++impl_->midiOverflow;impl_->allNotesOff(0,true);}}
void Engine::renderSilence(std::span<float>l,std::span<float>r)noexcept{std::ranges::fill(l,0);std::ranges::fill(r,0);}int Engine::latencySamples()const noexcept{return impl_->oversampling?static_cast<int>(std::ceil(impl_->oversampling->getLatencyInSamples())):0;}std::uint64_t Engine::guardHits()const noexcept{return impl_->guardHits;}std::uint64_t Engine::midiOverflowCount()const noexcept{return impl_->midiOverflow;}std::size_t Engine::activeVoiceCount()const noexcept{return std::ranges::count_if(impl_->voices,[](auto&v){return v.active;});}
void Engine::effectiveValues(EffectiveValues&out)const noexcept
{
 const auto&patch=impl_->patch;const Impl::Voice*newest=nullptr;for(const auto&v:impl_->voices)if(v.active&&(!newest||v.age>newest->age))newest=&v;
 const VoiceValues*voiceValues=nullptr;if(newest){if(newest->usingTransition)voiceValues=&newest->transitionValues;else if(newest->modulationReady)voiceValues=&newest->modulatedValues;}
 // An effects node is not inside any voice, so its ring comes from the tail's own macro-only pass.
 const VoiceValues*tailModulated=impl_->tailModulationReady?&impl_->tailValues:nullptr;
 out.nodeCount=patch.nodeCount;
 for(std::size_t n=0;n<domain::maximumNodes;++n){const bool live=n<patch.nodeCount;out.nodeIds[n]=live?patch.nodes[n].idHash:0u;for(std::size_t t=0;t<parameterTargetCount;++t){const auto&range=patch.nodes[n].ranges[t];if(!live||!range.eligible){out.values[n][t]=-1.f;continue;}const auto target=static_cast<ParameterTarget>(t);const auto*source=n>=patch.tailStart?tailModulated:voiceValues;const float raw=targetValue(source?(*source)[n]:patch.nodes[n].values,target);out.values[n][t]=normalize(raw,range);}}
}
}
