#include "iupac/engine/Engine.hpp"

#include <algorithm>
#include <cmath>
#include <map>
#include <set>
#include <string_view>
#include <vector>

namespace iupac::engine {
namespace {
constexpr float safetyPeak=.891251f;
std::uint32_t hashId(std::string_view s) noexcept {std::uint32_t h=2166136261u;for(auto c:s){h^=static_cast<std::uint8_t>(c);h*=16777619u;}return h;}
const domain::ParameterValue* valueOf(const domain::Node& n,std::string_view id){auto i=std::ranges::find(n.parameters,id,&domain::ParameterValue::id);return i==n.parameters.end()?nullptr:&*i;}
float scalar(const domain::Node& n,std::string_view id,float fallback){auto* v=valueOf(n,id);return v&&!v->values.empty()?static_cast<float>(v->values[0]):fallback;}
ModuleValues moduleValues(const domain::Node& n){ModuleValues v;auto copy=[&](std::string_view id,auto& d){if(auto* s=valueOf(n,id))for(std::size_t i=0;i<std::min(d.size(),s->values.size());++i)d[i]=static_cast<float>(s->values[i]);};copy("partialAmplitudes",v.amplitudes);copy("partialRatios",v.ratios);copy("partialPans",v.pans);copy("modeRatios",v.modeRatios);copy("modeLevels",v.modeLevels);v.carrierRatio=scalar(n,"carrierRatio",1);v.modulatorRatio=scalar(n,"modulatorRatio",1);v.index=scalar(n,"index",0);v.burstMilliseconds=scalar(n,"burstMs",80);v.tuneRatio=scalar(n,"tuneRatio",1);v.combFeedback=scalar(n,"combFeedback",.4f);v.modalQ=scalar(n,"modalQ",3);v.cutoff=scalar(n,"cutoff",1000);v.q=scalar(n,"q",.707f);v.drive=scalar(n,"drive",1);v.wet=scalar(n,"wet",1);v.level=scalar(n,"level",1);v.pan=scalar(n,"pan",0);v.outputLevel=scalar(n,"outputLevel",1);v.mode=static_cast<int>(scalar(n,"mode",0));v.color=static_cast<int>(scalar(n,"color",0));return v;}
std::optional<ParameterTarget> targetFor(std::string_view id){static constexpr std::array<std::pair<std::string_view,ParameterTarget>,14> p{{{"carrierRatio",ParameterTarget::carrierRatio},{"modulatorRatio",ParameterTarget::modulatorRatio},{"index",ParameterTarget::index},{"burstMs",ParameterTarget::burstMilliseconds},{"tuneRatio",ParameterTarget::tuneRatio},{"combFeedback",ParameterTarget::combFeedback},{"modalQ",ParameterTarget::modalQ},{"cutoff",ParameterTarget::cutoff},{"q",ParameterTarget::q},{"drive",ParameterTarget::drive},{"wet",ParameterTarget::wet},{"level",ParameterTarget::level},{"pan",ParameterTarget::pan},{"outputLevel",ParameterTarget::outputLevel}}};for(auto [name,target]:p)if(id==name)return target;return{};}
float& targetValue(ModuleValues& v,ParameterTarget t) noexcept {switch(t){case ParameterTarget::carrierRatio:return v.carrierRatio;case ParameterTarget::modulatorRatio:return v.modulatorRatio;case ParameterTarget::index:return v.index;case ParameterTarget::burstMilliseconds:return v.burstMilliseconds;case ParameterTarget::tuneRatio:return v.tuneRatio;case ParameterTarget::combFeedback:return v.combFeedback;case ParameterTarget::modalQ:return v.modalQ;case ParameterTarget::cutoff:return v.cutoff;case ParameterTarget::q:return v.q;case ParameterTarget::drive:return v.drive;case ParameterTarget::wet:return v.wet;case ParameterTarget::level:return v.level;case ParameterTarget::pan:return v.pan;case ParameterTarget::outputLevel:return v.outputLevel;}return v.outputLevel;}
float normalize(float v,const CompiledRow&r)noexcept{v=std::clamp(v,r.minimum,r.maximum);return r.scale==domain::ParameterScale::logarithmic?std::log(v/r.minimum)/std::log(r.maximum/r.minimum):(v-r.minimum)/(r.maximum-r.minimum);}
float denormalize(float v,const CompiledRow&r)noexcept{v=std::clamp(v,0.f,1.f);return r.scale==domain::ParameterScale::logarithmic?r.minimum*std::pow(r.maximum/r.minimum,v):r.minimum+v*(r.maximum-r.minimum);}
float lerpValue(float a,float b,float x)noexcept{return std::lerp(a,b,x);}
ModuleValues interpolate(const ModuleValues&a,const ModuleValues&b,float x)noexcept{ModuleValues r=b;for(std::size_t i=0;i<r.amplitudes.size();++i){r.amplitudes[i]=lerpValue(a.amplitudes[i],b.amplitudes[i],x);r.ratios[i]=lerpValue(a.ratios[i],b.ratios[i],x);r.pans[i]=lerpValue(a.pans[i],b.pans[i],x);}for(std::size_t i=0;i<r.modeRatios.size();++i){r.modeRatios[i]=lerpValue(a.modeRatios[i],b.modeRatios[i],x);r.modeLevels[i]=lerpValue(a.modeLevels[i],b.modeLevels[i],x);}r.carrierRatio=lerpValue(a.carrierRatio,b.carrierRatio,x);r.modulatorRatio=lerpValue(a.modulatorRatio,b.modulatorRatio,x);r.index=lerpValue(a.index,b.index,x);r.burstMilliseconds=lerpValue(a.burstMilliseconds,b.burstMilliseconds,x);r.tuneRatio=lerpValue(a.tuneRatio,b.tuneRatio,x);r.combFeedback=lerpValue(a.combFeedback,b.combFeedback,x);r.modalQ=lerpValue(a.modalQ,b.modalQ,x);r.cutoff=lerpValue(a.cutoff,b.cutoff,x);r.q=lerpValue(a.q,b.q,x);r.drive=lerpValue(a.drive,b.drive,x);r.wet=lerpValue(a.wet,b.wet,x);r.level=lerpValue(a.level,b.level,x);r.pan=lerpValue(a.pan,b.pan,x);r.outputLevel=lerpValue(a.outputLevel,b.outputLevel,x);return r;}
domain::HostControls interpolate(const domain::HostControls&a,const domain::HostControls&b,float x)noexcept{domain::HostControls r=b;for(std::size_t i=0;i<r.macros.size();++i)r.macros[i]=std::lerp(a.macros[i],b.macros[i],static_cast<double>(x));r.outputGain=std::lerp(a.outputGain,b.outputGain,static_cast<double>(x));r.width=std::lerp(a.width,b.width,static_cast<double>(x));r.masterTune=std::lerp(a.masterTune,b.masterTune,static_cast<double>(x));return r;}
}

ModuleValues applyModulation(const CompiledPatch& patch,std::size_t node,const ModuleValues& base,const ModulationInputs& inputs)noexcept
{
 ModuleValues values=base;
 for(std::size_t targetIndex=0;targetIndex<=static_cast<std::size_t>(ParameterTarget::outputLevel);++targetIndex){
  auto target=static_cast<ParameterTarget>(targetIndex);const CompiledRow* definition=nullptr;float contribution=0;
  for(std::size_t rowIndex=0;rowIndex<patch.rowCount;++rowIndex){const auto&row=patch.rows[rowIndex];if(row.node==node&&row.target==target){definition=&row;contribution+=row.depth*inputs[static_cast<std::size_t>(row.source)];}}
  if(definition){auto&value=targetValue(values,target);value=denormalize(normalize(value,*definition)+contribution,*definition);}
 }
 return values;
}

CompileResult compilePatch(const domain::Patch& source){CompileResult result;if(auto e=domain::validate(source);!e.empty()){result.error=e;return result;}std::map<std::string,std::size_t,std::less<>> original;for(std::size_t i=0;i<source.nodes.size();++i)original.emplace(source.nodes[i].id,i);std::set<std::string,std::less<>> live;std::vector<std::string> frontier;for(auto&e:source.edges)if(e.destination=="output"&&live.insert(e.source).second)frontier.push_back(e.source);while(!frontier.empty()){auto d=frontier.back();frontier.pop_back();for(auto&e:source.edges)if(e.destination==d&&live.insert(e.source).second)frontier.push_back(e.source);}std::map<std::string,int,std::less<>> indegree;for(auto&id:live)indegree[id]=0;for(auto&e:source.edges)if(e.destination!="output"&&live.contains(e.source)&&live.contains(e.destination))++indegree[e.destination];std::set<std::string,std::less<>> ready;for(auto&[id,n]:indegree)if(!n)ready.insert(id);std::vector<std::string> order;while(!ready.empty()){auto id=*ready.begin();ready.erase(ready.begin());order.push_back(id);for(auto&e:source.edges)if(e.source==id&&e.destination!="output"&&live.contains(e.destination)&&!--indegree[e.destination])ready.insert(e.destination);}if(order.size()!=live.size()){result.error="compiler found cycle";return result;}std::map<std::string,std::uint8_t,std::less<>> slots;for(std::size_t i=0;i<order.size();++i){slots.emplace(order[i],static_cast<std::uint8_t>(i));auto&n=source.nodes[original.at(order[i])];result.patch.nodes[i]={n.type,moduleValues(n),hashId(n.id)};}result.patch.nodeCount=static_cast<std::uint8_t>(order.size());for(auto&e:source.edges)if(live.contains(e.source)&&(e.destination=="output"||live.contains(e.destination))){auto&o=result.patch.edges[result.patch.edgeCount++];o.source=slots.at(e.source);o.gain=static_cast<float>(e.gain);o.toOutput=e.destination=="output";o.destination=o.toOutput?0:slots.at(e.destination);}for(auto&r:source.matrix)if(r.enabled&&live.contains(r.destinationNode)){auto slot=slots.at(r.destinationNode);auto&n=source.nodes[original.at(r.destinationNode)];auto&md=domain::moduleCatalog()[static_cast<std::size_t>(n.type)];auto*pd=domain::findParameter(md,r.destinationParameter);auto target=targetFor(r.destinationParameter);if(!pd||!target){result.error="unsupported matrix destination";return result;}result.patch.rows[result.patch.rowCount++]={r.source,slot,*target,static_cast<float>(r.depth),static_cast<float>(pd->minimum),static_cast<float>(pd->maximum),pd->scale};}result.patch.envelopes=source.envelopes;result.patch.lfos=source.lfos;result.patch.noiseSeed=source.noiseSeed;return result;}

class Engine::Impl {public:
 struct Voice{std::array<ModuleProcessor,domain::maximumNodes> modules;std::array<std::unique_ptr<ModuleProcessor::CombDelay>,2> combs;ModulatorBank modulators;std::array<float,domain::maximumNodes> left{},right{};int note{},channel{1};float velocity{},lastL{},lastR{},tailL{},tailR{},level{};std::uint32_t fade{};std::uint64_t age{};bool held{},sustained{},active{},forcedStop{};};
 std::array<Voice,maximumVoices> voices;std::array<float,16>bend{},cc1{};std::array<bool,16>sustain{};CompiledPatch patch{},previousPatch{};domain::HostControls controls{},previousControls{};std::uint64_t age{},guardHits{},midiOverflow{},smoothSample{},smoothLength{1};std::unique_ptr<juce::dsp::Oversampling<float>> oversampling;juce::dsp::Limiter<float> limiter;juce::AudioBuffer<float> output;double outputRate{48000};std::size_t maxBlock{};float dcXL{},dcYL{},dcXR{},dcYR{};
 void prepare(double rate,std::size_t block){outputRate=rate;maxBlock=std::max<std::size_t>(1,block);smoothLength=static_cast<std::uint64_t>(std::max(1.0,internalSampleRate(rate)*.020));output.setSize(2,static_cast<int>(maxBlock),false,false,true);oversampling=std::make_unique<juce::dsp::Oversampling<float>>(2,1,juce::dsp::Oversampling<float>::filterHalfBandPolyphaseIIR,true,true);oversampling->initProcessing(maxBlock);limiter.prepare({rate,static_cast<juce::uint32>(maxBlock),2});limiter.setThreshold(-1.f);limiter.setRelease(20.f);juce::dsp::ProcessSpec spec{internalSampleRate(rate),static_cast<juce::uint32>(maxBlock*2),2};for(auto&v:voices){v.modulators.prepare(internalSampleRate(rate));for(auto&c:v.combs){c=std::make_unique<ModuleProcessor::CombDelay>(110000);c->prepare(spec);}for(auto&m:v.modules)m.prepare(internalSampleRate(rate),maxBlock*2);}reset();}
 void reset()noexcept{bend.fill(0);cc1.fill(0);sustain.fill(false);age=guardHits=midiOverflow=0;dcXL=dcYL=dcXR=dcYR=0;if(oversampling)oversampling->reset();limiter.reset();for(auto&v:voices){v.active=v.held=v.sustained=v.forcedStop=false;v.fade=0;v.lastL=v.lastR=v.tailL=v.tailR=v.level=0;v.modulators.reset();for(auto&m:v.modules)m.reset();}}
 void configure(Voice&v)noexcept{v.modulators.configure(patch.envelopes,patch.lfos);std::size_t comb=0;for(std::size_t i=0;i<patch.nodeCount;++i){v.modules[i].setCombDelay(patch.nodes[i].type==domain::ModuleType::resonator?v.combs[comb++].get():nullptr);v.modules[i].setType(patch.nodes[i].type);}}
 void noteOn(int ch,int note,float velocity){Voice*pick=nullptr;for(auto&v:voices)if(!v.active){pick=&v;break;}if(!pick)for(auto&v:voices)if(!v.held&&(!pick||v.level<pick->level||(v.level==pick->level&&v.age<pick->age)))pick=&v;if(!pick)pick=&*std::ranges::min_element(voices,{},&Voice::age);if(pick->active){pick->tailL=pick->lastL;pick->tailR=pick->lastR;pick->fade=static_cast<std::uint32_t>(std::max(1.,internalSampleRate(outputRate)*.005));}else{pick->tailL=pick->tailR=0;pick->fade=0;}for(auto&m:pick->modules)m.reset();pick->modulators.configure(patch.envelopes,patch.lfos);pick->modulators.reset();pick->note=note;pick->channel=ch;pick->velocity=velocity;pick->level=0;pick->age=++age;pick->active=pick->held=true;pick->sustained=pick->forcedStop=false;pick->modulators.noteOn();for(std::size_t i=0;i<patch.nodeCount;++i)pick->modules[i].noteOn(note,ch,patch.noiseSeed,patch.nodes[i].idHash);}
 void noteOff(int ch,int note)noexcept{Voice*old=nullptr;for(auto&v:voices)if(v.active&&v.held&&v.channel==ch&&v.note==note&&(!old||v.age<old->age))old=&v;if(!old)return;old->held=false;if(sustain[ch-1])old->sustained=true;else old->modulators.noteOff();}
 void allNotesOff(int ch,bool immediate)noexcept{for(auto&v:voices)if(v.active&&(!ch||v.channel==ch)){v.held=v.sustained=false;v.modulators.noteOff();if(immediate){v.forcedStop=true;v.tailL=v.lastL;v.tailR=v.lastR;v.fade=static_cast<std::uint32_t>(std::max(1.,internalSampleRate(outputRate)*.005));}}}
 void event(const MidiEvent&e){if(e.channel<1||e.channel>16||e.data1>127||e.data2>127||e.bend>16383)return;auto ch=static_cast<int>(e.channel);if(e.type==MidiEventType::noteOn){if(!e.data2)noteOff(ch,e.data1);else noteOn(ch,e.data1,e.data2/127.f);}else if(e.type==MidiEventType::noteOff)noteOff(ch,e.data1);else if(e.type==MidiEventType::pitchBend)bend[ch-1]=std::clamp((static_cast<int>(e.bend)-8192)/8192.f,-1.f,1.f);else if(e.type==MidiEventType::controlChange&&e.data1==1)cc1[ch-1]=e.data2/127.f;else if(e.type==MidiEventType::controlChange&&e.data1==64){bool down=e.data2>=64;if(sustain[ch-1]&&!down)for(auto&v:voices)if(v.active&&v.channel==ch&&v.sustained){v.sustained=false;v.modulators.noteOff();}sustain[ch-1]=down;}else if(e.type==MidiEventType::controlChange&&e.data1==120)allNotesOff(ch,true);else if(e.type==MidiEventType::controlChange&&e.data1==123)allNotesOff(ch,false);}
 float source(domain::ModulationSource s,const Voice&v,const std::array<float,5>&m)const noexcept{auto i=static_cast<std::size_t>(s);if(i<5)return m[i];switch(s){case domain::ModulationSource::velocity:return v.velocity;case domain::ModulationSource::keyTracking:return std::clamp((v.note-60)/36.f,-1.f,1.f);case domain::ModulationSource::pitchBend:return bend[v.channel-1];case domain::ModulationSource::cc1:return cc1[v.channel-1];case domain::ModulationSource::macro1:case domain::ModulationSource::macro2:case domain::ModulationSource::macro3:case domain::ModulationSource::macro4:{const float x=smoothSample>=smoothLength?1.f:static_cast<float>(smoothSample)/static_cast<float>(smoothLength);const auto macro=i-static_cast<std::size_t>(domain::ModulationSource::macro1);return std::lerp(static_cast<float>(previousControls.macros[macro]),static_cast<float>(controls.macros[macro]),x);}default:return 0;}}
 void renderInternal(juce::dsp::AudioBlock<float>&b,std::size_t begin,std::size_t end)noexcept{auto*lout=b.getChannelPointer(0);auto*rout=b.getChannelPointer(1);for(std::size_t s=begin*2;s<end*2;++s){const float x=smoothSample>=smoothLength?1.f:static_cast<float>(smoothSample)/static_cast<float>(smoothLength);const auto blockControls=interpolate(previousControls,controls,x);float sumL=0,sumR=0;for(auto&v:voices)if(v.active){auto mods=v.modulators.next();ModulationInputs inputs{};for(std::size_t i=0;i<inputs.size();++i)inputs[i]=source(static_cast<domain::ModulationSource>(i),v,mods);std::array<ModuleValues,domain::maximumNodes> values{};for(std::size_t n=0;n<patch.nodeCount;++n){const auto oldValues=applyModulation(previousPatch,n,previousPatch.nodes[n].values,inputs);const auto newValues=applyModulation(patch,n,patch.nodes[n].values,inputs);values[n]=interpolate(oldValues,newValues,x);if(patch.nodes[n].type==domain::ModuleType::filter)values[n].cutoff=std::min(values[n].cutoff,filterCutoffCeiling(outputRate));float inL=0,inR=0;for(std::size_t e=0;e<patch.edgeCount;++e){auto&edge=patch.edges[e];const float edgeGain=std::lerp(previousPatch.edges[e].gain,edge.gain,x);if(!edge.toOutput&&edge.destination==n){inL+=v.left[edge.source]*edgeGain;inR+=v.right[edge.source]*edgeGain;}}float tune=static_cast<float>(blockControls.masterTune)+2*bend[v.channel-1];float hz=440*std::pow(2.f,(v.note-69+tune)/12.f);v.modules[n].process(values[n],hz,{&inL,1},{&inR,1},{&v.left[n],1},{&v.right[n],1});}float l=0,r=0;for(std::size_t e=0;e<patch.edgeCount;++e)if(patch.edges[e].toOutput){const float edgeGain=std::lerp(previousPatch.edges[e].gain,patch.edges[e].gain,x);l+=v.left[patch.edges[e].source]*edgeGain;r+=v.right[patch.edges[e].source]*edgeGain;}l*=mods[0]*v.velocity;r*=mods[0]*v.velocity;if(v.fade){const auto fadeTotal=static_cast<float>(std::max(1.,internalSampleRate(outputRate)*.005));const float f=std::min(1.f,v.fade/fadeTotal);if(v.forcedStop){l=v.tailL*f;r=v.tailR*f;}else{l=l*(1-f)+v.tailL*f;r=r*(1-f)+v.tailR*f;}--v.fade;}v.lastL=l;v.lastR=r;v.level=.999f*v.level+.001f*std::max(std::abs(l),std::abs(r));sumL+=l;sumR+=r;if((v.forcedStop&&!v.fade)||(!v.modulators.finalEnvelopeActive()&&!v.held&&!v.sustained&&!v.fade)){v.active=false;v.forcedStop=false;for(auto&m:v.modules)m.reset();}}float mid=(sumL+sumR)*.5f,side=(sumL-sumR)*static_cast<float>(blockControls.width);sumL=mid+side;sumR=mid-side;float gain=std::pow(10.f,static_cast<float>(blockControls.outputGain)/20.f);sumL*=gain;sumR*=gain;float dl=sumL-dcXL+.995f*dcYL,dr=sumR-dcXR+.995f*dcYR;dcXL=sumL;dcYL=dl;dcXR=sumR;dcYR=dr;auto safe=[this](float v){if(!std::isfinite(v)){++guardHits;return 0.f;}if(std::abs(v)>safetyPeak){++guardHits;v=std::clamp(v,-safetyPeak,safetyPeak);}return v;};lout[s]=blockControls.bypass?0:safe(dl);rout[s]=blockControls.bypass?0:safe(dr);if(smoothSample<smoothLength)++smoothSample;}}
};
Engine::Engine():impl_(std::make_unique<Impl>()){}Engine::~Engine()=default;Engine::Engine(Engine&&)noexcept=default;Engine&Engine::operator=(Engine&&)noexcept=default;
void Engine::prepare(double r,std::size_t b)noexcept{sampleRate_=std::max(1.,r);maximumBlockSize_=std::max<std::size_t>(1,b);impl_->prepare(sampleRate_,maximumBlockSize_);}void Engine::reset()noexcept{impl_->reset();}void Engine::setPatch(const CompiledPatch&p){impl_->patch=impl_->previousPatch=p;impl_->smoothSample=impl_->smoothLength;for(auto&v:impl_->voices)impl_->configure(v);impl_->reset();}void Engine::setControls(const domain::HostControls&c)noexcept{impl_->previousControls=impl_->controls;impl_->controls=c;impl_->smoothSample=0;}
void Engine::updatePatchPreservingVoices(const CompiledPatch&p)noexcept{impl_->previousPatch=impl_->patch;impl_->patch=p;impl_->smoothSample=0;for(auto&v:impl_->voices)v.modulators.configure(p.envelopes,p.lfos);}
void Engine::render(std::span<float>left,std::span<float>right,std::span<const MidiEvent>events)noexcept{auto total=std::min(left.size(),right.size());if(!total)return;std::size_t offset=0,eventIndex=0,processed=0;while(offset<total){auto count=std::min(maximumBlockSize_,total-offset);impl_->output.clear();juce::dsp::AudioBlock<float>base(impl_->output);auto slice=base.getSubBlock(0,count);auto up=impl_->oversampling->processSamplesUp(slice);up.clear();std::size_t cursor=0;while(eventIndex<events.size()&&events[eventIndex].sampleOffset<offset+count&&processed<maximumMidiEventsPerBlock){auto eo=std::max<std::size_t>(cursor,events[eventIndex].sampleOffset>offset?events[eventIndex].sampleOffset-offset:0);impl_->renderInternal(up,cursor,eo);impl_->event(events[eventIndex]);cursor=eo;++eventIndex;++processed;}impl_->renderInternal(up,cursor,count);impl_->oversampling->processSamplesDown(slice);juce::dsp::ProcessContextReplacing<float>context(slice);impl_->limiter.process(context);for(std::size_t i=0;i<count;++i){auto guard=[this](float x){if(!std::isfinite(x)){++impl_->guardHits;return 0.f;}if(std::abs(x)>safetyPeak){++impl_->guardHits;return std::clamp(x,-safetyPeak,safetyPeak);}return x;};left[offset+i]=guard(impl_->output.getSample(0,static_cast<int>(i)));right[offset+i]=guard(impl_->output.getSample(1,static_cast<int>(i)));}offset+=count;}if(eventIndex<events.size()){++impl_->midiOverflow;impl_->allNotesOff(0,true);}}
void Engine::renderSilence(std::span<float>l,std::span<float>r)noexcept{std::ranges::fill(l,0);std::ranges::fill(r,0);}int Engine::latencySamples()const noexcept{return impl_->oversampling?static_cast<int>(std::ceil(impl_->oversampling->getLatencyInSamples())):0;}std::uint64_t Engine::guardHits()const noexcept{return impl_->guardHits;}std::uint64_t Engine::midiOverflowCount()const noexcept{return impl_->midiOverflow;}std::size_t Engine::activeVoiceCount()const noexcept{return std::ranges::count_if(impl_->voices,[](auto&v){return v.active;});}
}
