#pragma once

// Fixed editor slot geometry (D6 editor baseline, #69; widened by D8, #109). JUCE-free data: the
// sixteen typed slots plus the OUT bus at code-time positions in a 1000x700 reference frame, layered
// left to right SRC(3)+SUB | RES(2) | FILT(2) | SHAPE(2) | MIX(2) | FX(4) | OUT, where the FX band is
// the global post-mixer effects tail and holds one chorus, delay, reverb and width slot. The numbers are generated offline by
// scripts/layout-slots.py (Graphviz dot over scripts/layout-slots.dot, the complete eligible-edge
// graph) and committed; `scripts/layout-slots.py --check include/iupac/ui/Layout.hpp` reproduces
// them. Scaling to the live window is a pure function of the window size. No free-form
// placement and no saved layouts exist.
#include <array>
#include <cstddef>
#include <optional>
#include <string_view>

namespace iupac::ui
{
inline constexpr double referenceWidth = 1000.0;
inline constexpr double referenceHeight = 700.0;
inline constexpr int columnCount = 7;
inline constexpr std::size_t slotCount = 17;
inline constexpr std::size_t outputSlot = 16; // the OUT bus row of slotTable

enum class SlotKind { source, sub, resonator, filter, shaper, mixer, chorus, delay, reverb, width, output };

struct Point
{
    double x{};
    double y{};
};

struct Rect
{
    double x{};
    double y{};
    double width{};
    double height{};
    [[nodiscard]] constexpr double right() const noexcept { return x + width; }
    [[nodiscard]] constexpr double bottom() const noexcept { return y + height; }
    [[nodiscard]] constexpr Point centre() const noexcept { return {x + width / 2.0, y + height / 2.0}; }
};

struct Slot
{
    SlotKind kind{};
    int instance{}; // 0-based index within the kind, numbered top to bottom
    int column{};
    Rect frame{};   // reference-frame rectangle
    [[nodiscard]] constexpr bool hasInput() const noexcept { return kind != SlotKind::source && kind != SlotKind::sub; }
    // The effects region is the global post-mixer tail: its OUT may only reach another effects slot
    // or the OUT bus (ARCHITECTURE "Effects region and the global tail").
    [[nodiscard]] constexpr bool isEffects() const noexcept { return kind >= SlotKind::chorus && kind <= SlotKind::width; }
    [[nodiscard]] constexpr bool hasOutput() const noexcept { return kind != SlotKind::output; }
    // Ports: one IN anchor on the left border, one OUT anchor on the right border, both at mid height.
    [[nodiscard]] constexpr Point inputAnchor() const noexcept { return {frame.x, frame.y + frame.height / 2.0}; }
    [[nodiscard]] constexpr Point outputAnchor() const noexcept { return {frame.right(), frame.y + frame.height / 2.0}; }
};

// Generated by scripts/layout-slots.py; do not edit the numbers by hand.
inline constexpr std::array<Slot, slotCount> slotTable {{
    {SlotKind::source, 0, 0, {20.0, 70.0, 104.2, 124.5}}, // SRC1
    {SlotKind::source, 1, 0, {20.0, 208.5, 104.2, 124.5}}, // SRC2
    {SlotKind::source, 2, 0, {20.0, 347.0, 104.2, 124.5}}, // SRC3
    {SlotKind::sub, 0, 0, {20.0, 485.5, 104.2, 124.5}}, // SUB
    {SlotKind::resonator, 0, 1, {170.4, 208.5, 104.2, 124.5}}, // RES1
    {SlotKind::resonator, 1, 1, {170.4, 347.0, 104.2, 124.5}}, // RES2
    {SlotKind::filter, 0, 2, {320.7, 208.5, 104.2, 124.5}}, // FILT1
    {SlotKind::filter, 1, 2, {320.7, 347.0, 104.2, 124.5}}, // FILT2
    {SlotKind::shaper, 0, 3, {471.1, 208.5, 104.2, 124.5}}, // SHAPE1
    {SlotKind::shaper, 1, 3, {471.1, 347.0, 104.2, 124.5}}, // SHAPE2
    {SlotKind::mixer, 0, 4, {621.4, 208.5, 104.2, 124.5}}, // MIX1
    {SlotKind::mixer, 1, 4, {621.4, 347.0, 104.2, 124.5}}, // MIX2
    {SlotKind::chorus, 0, 5, {771.8, 70.0, 104.2, 124.5}}, // FX1
    {SlotKind::delay, 0, 5, {771.8, 208.5, 104.2, 124.5}}, // FX2
    {SlotKind::reverb, 0, 5, {771.8, 347.0, 104.2, 124.5}}, // FX3
    {SlotKind::width, 0, 5, {771.8, 485.5, 104.2, 124.5}}, // FX4
    {SlotKind::output, 0, 6, {922.1, 277.8, 57.9, 124.5}}, // OUT
}};

[[nodiscard]] constexpr std::string_view slotKindName(SlotKind kind) noexcept
{
    switch (kind)
    {
        case SlotKind::source: return "SRC";
        case SlotKind::sub: return "SUB";
        case SlotKind::resonator: return "RES";
        case SlotKind::filter: return "FILT";
        case SlotKind::shaper: return "SHAPE";
        case SlotKind::mixer: return "MIX";
        case SlotKind::chorus: return "CHORUS";
        case SlotKind::delay: return "DELAY";
        case SlotKind::reverb: return "REVERB";
        case SlotKind::width: return "WIDTH";
        case SlotKind::output: return "OUT";
    }
    return "";
}

[[nodiscard]] constexpr std::optional<std::size_t> findSlot(SlotKind kind, int instance) noexcept
{
    for (std::size_t i = 0; i < slotTable.size(); ++i)
        if (slotTable[i].kind == kind && slotTable[i].instance == instance) return i;
    return std::nullopt;
}

// Field extents in the reference frame: the cable corridor above the field and the return
// channel below it are the frame regions outside [fieldTop, fieldBottom).
[[nodiscard]] constexpr double fieldTop() noexcept
{
    double top = referenceHeight;
    for (const auto& slot : slotTable) top = slot.frame.y < top ? slot.frame.y : top;
    return top;
}

[[nodiscard]] constexpr double fieldBottom() noexcept
{
    double bottom = 0.0;
    for (const auto& slot : slotTable) bottom = slot.frame.bottom() > bottom ? slot.frame.bottom() : bottom;
    return bottom;
}

// Smallest vertical scale the live field is ever drawn at: the editor's minimum window is 1000x700
// and its fixed bands (macro strip, modulator row, lane table, keyboard) leave the field 396 px of
// the 700 reference units. Overlays painted at a fixed pixel size (the cable gain knob) reserve
// their room in reference units through this factor; `EditorTests` pins it against the real editor.
inline constexpr double minimumFieldHeight = 396.0;
inline constexpr double minimumFieldVerticalScale = minimumFieldHeight / referenceHeight;

// Text scale (#89). Captions and control text are authored as heights in the 1000x700 reference
// frame and multiplied by `textScale` of the live editor, so they grow with the window exactly like
// the geometry around them. The smaller of the two axis scales is used: a window stretched in one
// direction only must not push text out of the slot it labels. `minimumFontHeight` is the absolute
// legibility floor and is the height every reference size collapses to at and below the reference
// frame, where the scale is 1.
inline constexpr double minimumFontHeight = 8.0;

[[nodiscard]] constexpr double textScale(double windowWidth, double windowHeight) noexcept
{
    const double sx = windowWidth / referenceWidth, sy = windowHeight / referenceHeight;
    return sx < sy ? sx : sy;
}

[[nodiscard]] constexpr double fontHeight(double referenceFontHeight, double scale) noexcept
{
    const double height = referenceFontHeight * scale;
    return height < minimumFontHeight ? minimumFontHeight : height;
}

// Inter-column channel `c` (0..columnCount-2) is the horizontal gap between column c and c+1.
struct Channel
{
    double left{};
    double right{};
};

[[nodiscard]] constexpr Channel channelExtent(int channel) noexcept
{
    Channel extent {0.0, referenceWidth};
    for (const auto& slot : slotTable)
    {
        if (slot.column == channel && slot.frame.right() > extent.left) extent.left = slot.frame.right();
        if (slot.column == channel + 1 && slot.frame.x < extent.right) extent.right = slot.frame.x;
    }
    return extent;
}

// Pure scaling from the reference frame to a live window of the given size.
[[nodiscard]] constexpr Point scaleToWindow(Point point, double windowWidth, double windowHeight) noexcept
{
    return {point.x * windowWidth / referenceWidth, point.y * windowHeight / referenceHeight};
}

[[nodiscard]] constexpr Rect scaleToWindow(Rect rect, double windowWidth, double windowHeight) noexcept
{
    const double sx = windowWidth / referenceWidth, sy = windowHeight / referenceHeight;
    return {rect.x * sx, rect.y * sy, rect.width * sx, rect.height * sy};
}
}
