#!/usr/bin/env python3
"""Regenerate data/mapping-coverage.json from generation traces (mapper v3, D13).

usage: build_mapping_coverage.py <iupac-cli> <panel traces.json> [<more traces.json> ...] [--check]

The first trace file is the frozen panel's (`mapping-calibration` writes it); later files are
optional wider samples. A parameter is
  mapped    — a rule assigns it on the frozen panel (the calibration gate re-checks that);
  offPanel  — a rule assigns it, but only for structures the frozen panel does not contain;
  unmapped  — the mapper leaves it at its catalog default (D13: curated beats complete).
Drivers and rule ids are copied from the trace, never typed in.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "data/mapping-coverage.json"


def assignments(path):
    found = {}
    for trace in json.loads(Path(path).read_text()).values():
        if "patch" not in trace:
            continue
        types = {node["id"]: node["type"] for node in trace["patch"]["nodes"]}
        for item in trace["rules"]:
            if item["kind"] != "parameter":
                continue
            node, parameter = item["id"].split(".", 1)
            entry = found.setdefault((types[node], parameter), {"rules": set(), "drivers": set()})
            entry["rules"].add(item["ruleId"]); entry["drivers"].update(item["drivers"])
    return found


def build(cli, trace_files):
    catalog = json.loads(subprocess.run([cli, "inspect", "--stage", "catalog"], capture_output=True, text=True, check=True).stdout)
    panel = assignments(trace_files[0])
    wider = {}
    for path in trace_files[1:]:
        for key, value in assignments(path).items():
            entry = wider.setdefault(key, {"rules": set(), "drivers": set()})
            entry["rules"] |= value["rules"]; entry["drivers"] |= value["drivers"]
    entries = []
    for module in catalog["modules"]:
        for parameter in module["parameters"]:
            key = (module["id"], parameter["id"])
            source, status = (panel[key], "mapped") if key in panel else (wider[key], "offPanel") if key in wider else (None, "unmapped")
            entries.append({"module": key[0], "parameter": key[1], "status": status,
                            "ruleId": "+".join(sorted(source["rules"])) if source else "",
                            "drivers": sorted(source["drivers"]) if source else [],
                            "note": "" if status == "mapped" else "assigned only for structures outside the frozen panel" if status == "offPanel"
                                    else "left at the catalog default by mapper 3"})
    return {"coverageVersion": 4,
            "note": "Mapper 3 coverage (D13, #168), generated by tools/build_mapping_coverage.py from generation traces. "
                    "mapped = a rule assigns the parameter on the frozen panel; offPanel = a rule assigns it only for structures the panel "
                    "does not contain; unmapped = left at the catalog default. Drivers are trait names of SonicIntent 2; an empty driver "
                    "list on a mapped entry is a value the rule fixes rather than derives.",
            "entries": entries}


def main():
    arguments = [a for a in sys.argv[1:] if a != "--check"]
    text = json.dumps(build(arguments[0], arguments[1:]), indent=1) + "\n"
    if "--check" in sys.argv:
        if TARGET.read_text() != text:
            raise SystemExit("data/mapping-coverage.json is stale: rerun tools/build_mapping_coverage.py")
        return
    TARGET.write_text(text)
    counts = {}
    for entry in json.loads(text)["entries"]:
        counts[entry["status"]] = counts.get(entry["status"], 0) + 1
    print(counts)


if __name__ == "__main__":
    main()
